(function () {
  'use strict';

  // Apply dark mode before render to avoid flash
  (function () {
    if (localStorage.getItem('theme') === 'dark') {
      document.documentElement.setAttribute('data-theme', 'dark');
    }
  })();

  // ── i18n: 言語検出 + UI 文字列 ────────────────────────────────────
  var LANG = (function () {
    var l = (document.documentElement.lang || 'ja').toLowerCase();
    if (l.indexOf('en') === 0) return 'en';
    if (l.indexOf('es') === 0) return 'es';
    return 'ja';
  })();

  var UI_STRINGS = {
    ja: {
      menu: 'メニュー',
      search: '検索',
      searchPlaceholder: '記事を検索...（タイトル・カテゴリ）',
      searchHint: 'Esc で閉じる &nbsp;/&nbsp; ⌘K で開く',
      searchEmpty: '「{q}」に一致する記事が見つかりませんでした',
      darkMode: 'ダークモード切替',
      backToTop: 'ページ先頭に戻る',
      lightboxClose: '閉じる',
      tocLabel: 'この記事の内容',
      copy: 'コピー',
      copied: 'コピー済み',
      copyFailed: '失敗',
      copySource: '引用元: ',
      toastQuoted: '引用元URLを付加しました',
      mapAria: '{place}の地図を開く',
      previous: '← 前の記事',
      next: '次の記事 →',
      seriesViewAll: '{series} 一覧を見る',
      relatedLabel: 'こちらもどうぞ'
    },
    en: {
      menu: 'Menu',
      search: 'Search',
      searchPlaceholder: 'Search articles... (title or category)',
      searchHint: 'Esc to close &nbsp;/&nbsp; ⌘K to open',
      searchEmpty: 'No articles match "{q}"',
      darkMode: 'Toggle dark mode',
      backToTop: 'Back to top',
      lightboxClose: 'Close',
      tocLabel: 'In this article',
      copy: 'Copy',
      copied: 'Copied',
      copyFailed: 'Failed',
      copySource: 'Source: ',
      toastQuoted: 'Source URL added to clipboard',
      mapAria: 'Open map of {place}',
      previous: '← Previous',
      next: 'Next →',
      seriesViewAll: 'View all {series}',
      relatedLabel: 'You might also like'
    },
    es: {
      menu: 'Menú',
      search: 'Buscar',
      searchPlaceholder: 'Buscar artículos... (título o categoría)',
      searchHint: 'Esc para cerrar &nbsp;/&nbsp; ⌘K para abrir',
      searchEmpty: 'Ningún artículo coincide con "{q}"',
      darkMode: 'Cambiar modo oscuro',
      backToTop: 'Volver arriba',
      lightboxClose: 'Cerrar',
      tocLabel: 'En este artículo',
      copy: 'Copiar',
      copied: 'Copiado',
      copyFailed: 'Error',
      copySource: 'Fuente: ',
      toastQuoted: 'URL de la fuente añadida al portapapeles',
      mapAria: 'Abrir el mapa de {place}',
      previous: '← Anterior',
      next: 'Siguiente →',
      seriesViewAll: 'Ver toda la serie {series}',
      relatedLabel: 'También te puede interesar'
    }
  };

  // BEGIN: i18n-translations (auto-generated by scripts/build-stories.py)
  var I18N_TRANSLATIONS =   {
    "en": {
      "titles": {
        "hokkaido-sr400-day1.html": "Ōarai → Tomakomai by Sunflower Ferry: First Day in Sapporo [SR400 Hokkaido Tour ①]",
        "hokkaido-sr400-day2.html": "Sapporo to Wakkanai via Ishikari and the Ororon Line [SR400 Hokkaido Tour ②]",
        "hokkaido-sr400-day3.html": "Cape Sōya, the White Road, the Esanuka Line",
        "hokkaido-sr400-day4.html": "Monbetsu to Biei: Blue Pond and the Patchwork Road [SR400 Hokkaido Tour ④]",
        "hokkaido-sr400-day5.html": "Furano's Farm Tomita to Tomakomai: Sunflower Ferry Back to Ōarai [SR400 Hokkaido Tour ⑤]",
        "hokkaido-bear-spray.html": "Why You Need Bear Spray on a Shiretoko Tour: UDAP 12HP [Gear ③]",
        "hokkaido-routes.html": "Three Hokkaido Trips: Routes and Lodging from My SR400, Car, and XSR900 Tours",
        "taiwan.html": "Taiwan Travel Notes: Sunset at Keelung and the Lantern Release at Shifen Were Better Than I Expected",
        "costa-rica-intro.html": "What is Costa Rica Like? Nature, Safety, and Daily Life from a Former Resident",
        "costa-rica-irazu.html": "How to Visit Volcán Irazú: The Day I Couldn't See the Crater Lake",
        "costa-rica-christmas.html": "Christmas and New Year in Costa Rica: Tamales, Firecrackers, and the Festival of Light",
        "costa-rica-color-run.html": "Costa Rica's Japanese School and The Color Run: Children and a Festival in San José",
        "costa-rica-semana-santa.html": "Manuel Antonio National Park: Costa Rica During Semana Santa",
        "costa-rica-food.html": "Costa Rica & Central American Food: Gallo Pinto, Ceviche, Rice & Beans",
        "costa-rica-work.html": "Working as a Physical Therapist in Costa Rica: A Patient Who Walked Again with a Homemade Brace",
        "costa-rica-cano-negro.html": "Caño Negro and Monteverde: A New Year Trip Looking for Wildlife",
        "costa-rica-aribada.html": "Going to Ostional for the Arribada: The Day I Missed the Olive Ridley Mass Nesting",
        "nicaragua-ometepe-1.html": "Crossing the Border from Costa Rica to Nicaragua: TICA BUS to Ometepe Island",
        "nicaragua-ometepe-2.html": "One Day on Ometepe Island: Ojo de Agua and the Sights of a Volcanic Island",
        "nicaragua-granada.html": "Walking Granada: Colonial Nicaragua and the Soy Nica Leather Shop",
        "nicaragua-managua.html": "Managua and Masaya: Crafts Markets and Old Friends in Nicaragua's Capital",
        "nicaragua-leon.html": "Walking León: Sandinista Memory and the City of Rubén Darío",
        "nicaragua-flor-de-cana.html": "Touring the Flor de Caña Distillery: Tasting Nicaragua's Rum",
        "el-salvador-ruins.html": "Joya de Cerén and Tazumal: El Salvador's World Heritage and Maya Ruins",
        "el-salvador-volcan.html": "Climbing Santa Ana Volcano: Hiking to a Crater Lake with a Police Escort",
        "mexico-zocalo.html": "Mexico City Historic Center: Walking the Zócalo, Templo Mayor, and Cathedral",
        "mexico-guadalupe.html": "The Basílica de Guadalupe: Tepeyac Hill and the Miracle of the Tilma",
        "mexico-walk.html": "Walking Mexico City: Revolución Monument, Local Breakfast, and Street Art",
        "mexico-walmart.html": "Mexico Souvenirs: Walmart Is the Hidden Gem",
        "mexico-anthropology.html": "Ancient Mexico at the National Museum of Anthropology: The Sun Stone, Coatlicue, and Olmec Heads",
        "mexico-guanajuato.html": "Guanajuato, the &quot;Jewel Box City&quot;: Pípila at Night, the Alley of the Kiss, and the Mummy Museum",
        "mexico-teotihuacan.html": "Walking the Teotihuacán Ruins: Pyramid of the Sun, Pyramid of the Moon, and Temple of Quetzalcóatl",
        "mexico-palenque.html": "Palenque, the Maya City in the Jungle: Temple of the Inscriptions, Pakal's Tomb, and the Cross Group",
        "touring-camp-gear.html": "Solo Motorcycle Camping Gear: Tent, Sleeping Bag, and Pad [Camp Gear ①]",
        "camp-mori-makiba.html": "Mori-no-Makiba Auto Campground Review: A Winter Solo Camp, Pricing, and Atmosphere",
        "atsukan.html": "Hot Sake at Home: Manjukagami F60 and Hakkaisan Yukimuro 3-Year",
        "power-beam.html": "Fitting a Power Beam to the SR400: Vibration Reduction on Long-Distance Touring",
        "spanish-dictionary.html": "Choosing a Spanish Dictionary: Paper, Electronic, and App, Picked by Someone Who Lived in Central America",
        "bandai-azuma.html": "Riding the Bandai-Azuma Skyline: Volcanic Country in Fukushima",
        "five-color-lake.html": "Walking the Goshikinuma 'Five-Color Ponds' of Urabandai, Fukushima",
        "hokkaido-car-day1.html": "Aomori to Hakodate by Shinkansen: Walking the City at Night [Hokkaido Car Trip ①]",
        "hokkaido-car-day2.html": "Mt. Yōtei, Nikka Yoichi Distillery, and Otaru Canal [Hokkaido Car Trip ②]",
        "hokkaido-car-day3.html": "Shakotan Peninsula Drive: Bikuni Ōgon-misaki, Cape Kamui, and Sea Urchin at Kiyozushi [Hokkaido Car Trip ③]",
        "hokkaido-car-day4.html": "Hakodate Morning Market, Goryōkaku, and the &quot;First Step on Hokkaido&quot; Monument [Hokkaido Car Trip ④]",
        "touring-chiba-xsr900.html": "XSR900 Solo Tour in Chiba: Kasamori Kannon and the Bōsō Mountain Roads",
        "chile-1.html": "Walking Through Santiago: Chile's Supreme Court, Museums, and Historic Center",
        "chile-2.html": "Los Dominicos Crafts Market: Folk Crafts and a White Colonial Church in Santiago",
        "chile-3.html": "Last Day in Santiago: Palta Reina and Pre-Christmas City Walks",
        "belize-1.html": "Arriving in Belize City: Caribbean Sunrise and a Walk Through Asian Grocery Stores",
        "belize-2.html": "Caye Caulker and a Great Blue Hole Scenic Flight: Belize from the Air",
        "belize-3.html": "Walking Belize City: The Swing Bridge and a Last Day",
        "zao-ginzan.html": "Zao and Ginzan Onsen, Two Days: Okama Crater Lake, an Open-Air Bath in the Forest, and a Taishō-Era Night",
        "himawari-tsunan.html": "Two Days in Niigata Summer: The Tsunan Sunflower Field and the Nagaoka Fireworks",
        "panama-1.html": "Visiting Panamá Viejo: 500-Year-Old Ruins and Spanish Colonial History",
        "panama.html": "Walking Casco Viejo and the Mercado de Mariscos: A World Heritage Old Town and a Fish Market",
        "panama-3.html": "Visiting the Miraflores Locks: Watching a Massive Ship Pass Through the Panama Canal",
        "costa-rica-2025.html": "Returning to Costa Rica After 10 Years: A Changed San José and the Same Pilsen",
        "noto-touring.html": "Touring the Noto Peninsula: Sōji-ji Soin Temple and Sashimi with Gold Leaf",
        "irako.html": "Cape Irago, Solo: A Year-End Coast Walk and a Lot of Wind in Aichi",
        "chiba-chibanians.html": "Visiting the Chibanian Stratotype: A Chiba Touring Day with a Wild Boar and a Bike Warning Light",
        "toro-daishi.html": "The Tōrōzaka Daishi Cut-Through Tunnel: Returning to Chiba's Photogenic Spot on the XSR900",
        "izu-touring.html": "Izu Peninsula Two-Day Tour: Ashinoko Skyline and the West Izu Route",
        "motorcycle-show-2026.html": "Tokyo Motorcycle Show 2026: Bikes and Side Bags That Caught My Eye",
        "long-haul-flight-tips.html": "Surviving Long-Haul Flights: Small Tweaks to Make Economy a Little More Comfortable"
      },
      "tags": {
        "hokkaido-sr400-day1.html": "Hokkaido",
        "hokkaido-sr400-day2.html": "Hokkaido",
        "hokkaido-sr400-day3.html": "Hokkaido",
        "hokkaido-sr400-day4.html": "Hokkaido",
        "hokkaido-sr400-day5.html": "Hokkaido",
        "hokkaido-bear-spray.html": "Hokkaido",
        "hokkaido-routes.html": "Hokkaido",
        "taiwan.html": "Taiwan",
        "costa-rica-intro.html": "Costa Rica",
        "costa-rica-irazu.html": "Costa Rica",
        "costa-rica-christmas.html": "Costa Rica",
        "costa-rica-color-run.html": "Costa Rica",
        "costa-rica-semana-santa.html": "Costa Rica",
        "costa-rica-food.html": "Costa Rica",
        "costa-rica-work.html": "Costa Rica",
        "costa-rica-cano-negro.html": "Costa Rica",
        "costa-rica-aribada.html": "Costa Rica",
        "nicaragua-ometepe-1.html": "Nicaragua",
        "nicaragua-ometepe-2.html": "Nicaragua",
        "nicaragua-granada.html": "Nicaragua",
        "nicaragua-managua.html": "Nicaragua",
        "nicaragua-leon.html": "Nicaragua",
        "nicaragua-flor-de-cana.html": "Nicaragua",
        "el-salvador-ruins.html": "El Salvador",
        "el-salvador-volcan.html": "El Salvador",
        "mexico-zocalo.html": "Mexico",
        "mexico-guadalupe.html": "Mexico",
        "mexico-walk.html": "Mexico",
        "mexico-walmart.html": "Mexico",
        "mexico-anthropology.html": "Mexico",
        "mexico-guanajuato.html": "Mexico",
        "mexico-teotihuacan.html": "Mexico",
        "mexico-palenque.html": "Mexico",
        "touring-camp-gear.html": "キャンプ・ギア",
        "camp-mori-makiba.html": "Camping",
        "atsukan.html": "酒・グルメ",
        "power-beam.html": "バイク・ギア",
        "spanish-dictionary.html": "Spanish",
        "bandai-azuma.html": "Touring",
        "five-color-lake.html": "旅",
        "hokkaido-car-day1.html": "Hokkaido",
        "hokkaido-car-day2.html": "Hokkaido",
        "hokkaido-car-day3.html": "Hokkaido",
        "hokkaido-car-day4.html": "Hokkaido",
        "touring-chiba-xsr900.html": "Touring",
        "chile-1.html": "Chile",
        "chile-2.html": "Chile",
        "chile-3.html": "Chile",
        "belize-1.html": "Belize",
        "belize-2.html": "Belize",
        "belize-3.html": "Belize",
        "zao-ginzan.html": "Tohoku",
        "himawari-tsunan.html": "Niigata",
        "panama-1.html": "Panama",
        "panama.html": "Panama",
        "panama-3.html": "Panama",
        "costa-rica-2025.html": "Costa Rica",
        "noto-touring.html": "Touring",
        "irako.html": "Touring",
        "chiba-chibanians.html": "Touring",
        "toro-daishi.html": "Touring",
        "izu-touring.html": "Touring",
        "motorcycle-show-2026.html": "バイク",
        "long-haul-flight-tips.html": "International Travel"
      },
      "seriesLabels": {
        "コスタリカ滞在記": "Costa Rica Stories",
        "ニカラグア旅行記": "Nicaragua Travel Notes",
        "メキシコ旅行記": "Mexico Travel Notes",
        "メキシコ周遊記": "Mexico Tour Notes",
        "チリ旅行記": "Chile Travel Notes",
        "ベリーズ旅行記": "Belize Travel Notes",
        "エルサルバドル旅行記": "El Salvador Travel Notes",
        "パナマ旅行記": "Panama Travel Notes",
        "SR400北海道ツーリング": "SR400 Hokkaido Touring",
        "XSR900北海道ツーリング": "XSR900 Hokkaido Touring",
        "北海道車旅": "Hokkaido Car Trip",
        "装備編": "Gear Notes"
      }
    },
    "es": {
      "titles": {
        "hokkaido-sr400-day1.html": "De Ōarai a Tomakomai en el ferry Sunflower: primer día en Sapporo [SR400 Hokkaidō ①]",
        "hokkaido-sr400-day2.html": "De Sapporo a Wakkanai por Ishikari y la línea Ororon [SR400 Hokkaidō ②]",
        "hokkaido-sr400-day3.html": "Cabo Sōya, camino blanco, línea Esanuka",
        "hokkaido-sr400-day4.html": "De Monbetsu a Biei: Estanque Azul y la ruta Patchwork [SR400 Hokkaidō ④]",
        "hokkaido-sr400-day5.html": "Farm Tomita (Furano) a Tomakomai: ferry Sunflower de vuelta a Ōarai [SR400 Hokkaidō ⑤]",
        "hokkaido-bear-spray.html": "Por qué llevar spray antiosos en una ruta por Shiretoko: UDAP 12HP [Equipo ③]",
        "hokkaido-routes.html": "Tres viajes a Hokkaidō: rutas y alojamientos en SR400, coche y XSR900",
        "taiwan.html": "Crónicas de Taiwán: el atardecer en Keelung y soltar farolillos en Shifen, mejor de lo que esperaba",
        "costa-rica-intro.html": "¿Cómo es Costa Rica? Naturaleza, seguridad y vida cotidiana contadas por un exresidente",
        "costa-rica-irazu.html": "Cómo visitar el Volcán Irazú: el día en que no pude ver la laguna del cráter",
        "costa-rica-christmas.html": "Navidad y Año Nuevo en Costa Rica: tamales, pólvora y el Festival de la Luz",
        "costa-rica-color-run.html": "La Escuela Japonesa de Costa Rica y The Color Run: niños y fiesta en San José",
        "costa-rica-semana-santa.html": "Parque Nacional Manuel Antonio: Costa Rica en Semana Santa",
        "costa-rica-food.html": "Comida costarricense y centroamericana: gallo pinto, ceviche, rice and beans",
        "costa-rica-work.html": "Trabajando como fisioterapeuta en Costa Rica: un paciente que volvió a caminar con una férula casera",
        "costa-rica-cano-negro.html": "Caño Negro y Monteverde: un viaje de fin de año tras la fauna silvestre",
        "costa-rica-aribada.html": "A Ostional por la Arribada: el día en que llegué tarde al desove masivo de las loras",
        "nicaragua-ometepe-1.html": "Cruzando la frontera de Costa Rica a Nicaragua: en TICA BUS a la Isla de Ometepe",
        "nicaragua-ometepe-2.html": "Un día por la Isla de Ometepe: Ojo de Agua y los lugares de la isla volcánica",
        "nicaragua-granada.html": "Caminando por Granada: la Nicaragua colonial y la tienda de cuero Soy Nica",
        "nicaragua-managua.html": "Managua y Masaya: mercado de artesanías y reencuentro con amigos en la capital de Nicaragua",
        "nicaragua-leon.html": "Caminando por León: la memoria sandinista y la ciudad de Rubén Darío",
        "nicaragua-flor-de-cana.html": "Visita a la destilería Flor de Caña: probando el ron de Nicaragua",
        "el-salvador-ruins.html": "Joya de Cerén y Tazumal: el Patrimonio de la Humanidad y las ruinas mayas de El Salvador",
        "el-salvador-volcan.html": "Subiendo al Volcán Santa Ana: una caminata a la laguna del cráter con escolta policial",
        "mexico-zocalo.html": "Centro Histórico de Ciudad de México: caminando por el Zócalo, el Templo Mayor y la Catedral",
        "mexico-guadalupe.html": "La Basílica de Guadalupe: el Cerro del Tepeyac y el milagro de la tilma",
        "mexico-walk.html": "Caminando por Ciudad de México: Monumento a la Revolución, desayuno local y arte callejero",
        "mexico-walmart.html": "Souvenirs de México: Walmart, el lugar inesperado",
        "mexico-anthropology.html": "El México Antiguo en el Museo Nacional de Antropología: Piedra del Sol, Coatlicue y Cabezas Olmecas",
        "mexico-guanajuato.html": "Guanajuato, &quot;la Ciudad Joyero&quot;: el Pípila de Noche, el Callejón del Beso y el Museo de las Momias",
        "mexico-teotihuacan.html": "Caminando por las Ruinas de Teotihuacán: Pirámide del Sol, Pirámide de la Luna y Templo de Quetzalcóatl",
        "mexico-palenque.html": "Palenque, la ciudad maya en la selva: Templo de las Inscripciones, tumba de Pakal y el Grupo de las Cruces",
        "touring-camp-gear.html": "Equipo para acampada en moto en solitario: tienda, saco y aislante [Equipo de camping ①]",
        "camp-mori-makiba.html": "Reseña del Mori-no-Makiba Auto Campground: camping solo en invierno, precios y ambiente",
        "atsukan.html": "Sake caliente en casa: Manjukagami F60 y Hakkaisan Yukimuro 3 años",
        "power-beam.html": "Instalando un Power Beam en la SR400: reducción de vibraciones en ruta larga",
        "spanish-dictionary.html": "Cómo elegir un diccionario de español: papel, electrónico o app, visto desde Centroamérica",
        "bandai-azuma.html": "En moto por la Bandai-Azuma Skyline: zona volcánica en Fukushima",
        "five-color-lake.html": "Caminando por las 'lagunas de cinco colores' Goshikinuma, en Urabandai (Fukushima)",
        "hokkaido-car-day1.html": "De Aomori a Hakodate en Shinkansen: paseo nocturno por la ciudad [Viaje en coche por Hokkaidō ①]",
        "hokkaido-car-day2.html": "Monte Yōtei, destilería Nikka Yoichi y canal de Otaru [Viaje en coche por Hokkaidō ②]",
        "hokkaido-car-day3.html": "Ruta por la península de Shakotan: Bikuni Ōgon-misaki, cabo Kamui y un cuenco de erizo en Kiyozushi [Viaje en coche por Hokkaidō ③]",
        "hokkaido-car-day4.html": "Mercado matutino de Hakodate, Goryōkaku y monumento «Primer paso en Hokkaidō» [Viaje en coche por Hokkaidō ④]",
        "touring-chiba-xsr900.html": "Ruta solitaria por Chiba en XSR900: Kasamori Kannon y los caminos de montaña de Bōsō",
        "chile-1.html": "Caminando por Santiago: la Corte Suprema, museos y Centro Histórico de Chile",
        "chile-2.html": "Mercado Artesanal Los Dominicos: artesanías y la iglesia blanca de Santiago",
        "chile-3.html": "Último día en Santiago: Palta Reina y caminatas pre-navideñas",
        "belize-1.html": "Llegando a Belize City: amanecer caribeño y un paseo por supermercados asiáticos",
        "belize-2.html": "Cayo Caulker y vuelo panorámico al Gran Agujero Azul: Belice desde el aire",
        "belize-3.html": "Caminando por Belize City: el Swing Bridge y un último día",
        "zao-ginzan.html": "Zao y Ginzan Onsen, dos días: lago del cráter Okama, baño al aire libre en el bosque y una noche de era Taishō",
        "himawari-tsunan.html": "Dos días de verano en Niigata: el campo de girasoles de Tsunan y los fuegos de Nagaoka",
        "panama-1.html": "Visitando Panamá Viejo: ruinas de 500 años e historia colonial española",
        "panama.html": "Caminando por el Casco Viejo y el Mercado de Mariscos: el casco antiguo Patrimonio de la Humanidad y el mercado de pescado",
        "panama-3.html": "Visitando las esclusas de Miraflores: el momento en que un barco enorme atraviesa el Canal de Panamá",
        "costa-rica-2025.html": "Volviendo a Costa Rica después de 10 años: una San José cambiada y la misma Pilsen",
        "noto-touring.html": "En moto por la península de Noto: el templo Sōji-ji Soin y el sashimi con pan de oro",
        "irako.html": "Cabo Irago en solitario: caminata costera de fin de año y mucho viento en Aichi",
        "chiba-chibanians.html": "Visitando el estratotipo del Chibaniense: un día en moto por Chiba con un jabalí y la luz de motor encendida",
        "toro-daishi.html": "El túnel cortado en la roca de Tōrōzaka Daishi: regreso al spot fotogénico de Chiba en la XSR900",
        "izu-touring.html": "Ruta de dos días por la península de Izu: Ashinoko Skyline y la ruta del oeste",
        "motorcycle-show-2026.html": "Tokyo Motorcycle Show 2026: motos y alforjas que me llamaron la atención",
        "long-haul-flight-tips.html": "Sobrevivir a un vuelo de larga distancia: pequeños trucos para hacer la clase económica algo más cómoda"
      },
      "tags": {
        "hokkaido-sr400-day1.html": "Hokkaido",
        "hokkaido-sr400-day2.html": "Hokkaido",
        "hokkaido-sr400-day3.html": "Hokkaido",
        "hokkaido-sr400-day4.html": "Hokkaido",
        "hokkaido-sr400-day5.html": "Hokkaido",
        "hokkaido-bear-spray.html": "Hokkaido",
        "hokkaido-routes.html": "Hokkaido",
        "taiwan.html": "Taiwán",
        "costa-rica-intro.html": "Costa Rica",
        "costa-rica-irazu.html": "Costa Rica",
        "costa-rica-christmas.html": "Costa Rica",
        "costa-rica-color-run.html": "Costa Rica",
        "costa-rica-semana-santa.html": "Costa Rica",
        "costa-rica-food.html": "Costa Rica",
        "costa-rica-work.html": "Costa Rica",
        "costa-rica-cano-negro.html": "Costa Rica",
        "costa-rica-aribada.html": "Costa Rica",
        "nicaragua-ometepe-1.html": "Nicaragua",
        "nicaragua-ometepe-2.html": "Nicaragua",
        "nicaragua-granada.html": "Nicaragua",
        "nicaragua-managua.html": "Nicaragua",
        "nicaragua-leon.html": "Nicaragua",
        "nicaragua-flor-de-cana.html": "Nicaragua",
        "el-salvador-ruins.html": "El Salvador",
        "el-salvador-volcan.html": "El Salvador",
        "mexico-zocalo.html": "México",
        "mexico-guadalupe.html": "México",
        "mexico-walk.html": "México",
        "mexico-walmart.html": "México",
        "mexico-anthropology.html": "México",
        "mexico-guanajuato.html": "México",
        "mexico-teotihuacan.html": "México",
        "mexico-palenque.html": "México",
        "touring-camp-gear.html": "キャンプ・ギア",
        "camp-mori-makiba.html": "Camping",
        "atsukan.html": "酒・グルメ",
        "power-beam.html": "バイク・ギア",
        "spanish-dictionary.html": "Español",
        "bandai-azuma.html": "Moto",
        "five-color-lake.html": "旅",
        "hokkaido-car-day1.html": "Hokkaido",
        "hokkaido-car-day2.html": "Hokkaido",
        "hokkaido-car-day3.html": "Hokkaido",
        "hokkaido-car-day4.html": "Hokkaido",
        "touring-chiba-xsr900.html": "Moto",
        "chile-1.html": "Chile",
        "chile-2.html": "Chile",
        "chile-3.html": "Chile",
        "belize-1.html": "Belice",
        "belize-2.html": "Belice",
        "belize-3.html": "Belice",
        "zao-ginzan.html": "Tohoku",
        "himawari-tsunan.html": "Niigata",
        "panama-1.html": "Panamá",
        "panama.html": "Panamá",
        "panama-3.html": "Panamá",
        "costa-rica-2025.html": "Costa Rica",
        "noto-touring.html": "Moto",
        "irako.html": "Moto",
        "chiba-chibanians.html": "Moto",
        "toro-daishi.html": "Moto",
        "izu-touring.html": "Moto",
        "motorcycle-show-2026.html": "バイク",
        "long-haul-flight-tips.html": "Viajes internacionales"
      },
      "seriesLabels": {
        "コスタリカ滞在記": "Crónicas de Costa Rica",
        "ニカラグア旅行記": "Crónicas de Nicaragua",
        "メキシコ旅行記": "Crónicas de México",
        "メキシコ周遊記": "Recorrido por México",
        "チリ旅行記": "Crónicas de Chile",
        "ベリーズ旅行記": "Crónicas de Belice",
        "エルサルバドル旅行記": "Crónicas de El Salvador",
        "パナマ旅行記": "Crónicas de Panamá",
        "SR400北海道ツーリング": "SR400 Hokkaido en moto",
        "XSR900北海道ツーリング": "XSR900 Hokkaido en moto",
        "北海道車旅": "Hokkaido en coche",
        "装備編": "Notas de Equipo"
      }
    }
  };
  // END: i18n-translations

  function t(key, params) {
    var s = (UI_STRINGS[LANG] && UI_STRINGS[LANG][key]) || UI_STRINGS.ja[key] || key;
    if (params) {
      Object.keys(params).forEach(function (k) {
        s = s.replace(new RegExp('\\{' + k + '\\}', 'g'), params[k]);
      });
    }
    return s;
  }

  function articleTitle(file) {
    if (LANG !== 'ja' && I18N_TRANSLATIONS[LANG]) {
      var x = I18N_TRANSLATIONS[LANG].titles[file];
      if (x) return x;
    }
    for (var i = 0; i < ARTICLES.length; i++) if (ARTICLES[i].file === file) return ARTICLES[i].title;
    return file;
  }

  function articleTag(file) {
    if (LANG !== 'ja' && I18N_TRANSLATIONS[LANG]) {
      var x = I18N_TRANSLATIONS[LANG].tags[file];
      if (x) return x;
    }
    for (var i = 0; i < ARTICLES.length; i++) if (ARTICLES[i].file === file) return ARTICLES[i].tag;
    return '';
  }

  function seriesLabel(seriesNameJa) {
    if (LANG !== 'ja' && I18N_TRANSLATIONS[LANG]) {
      var x = I18N_TRANSLATIONS[LANG].seriesLabels[seriesNameJa];
      if (x) return x;
    }
    return seriesNameJa;
  }

  function isTranslated(file) {
    if (LANG === 'ja') return true;
    return !!(I18N_TRANSLATIONS[LANG] && I18N_TRANSLATIONS[LANG].titles[file]);
  }

  function storiesPath() {
    if (LANG === 'ja') return '../stories.html';
    return '../../' + LANG + '/stories.html';
  }

  var ARTICLES = [
    { file: 'hokkaido-sr400-day1.html',   title: '大洗からさんふらわあで苫小牧｜初日は札幌へ【SR400北海道ツーリング記録①】',                                                       category: 'bike',       tag: '北海道',           img: '../images/hokkaido/tomakomai-ferry.jpg',                                                                                  date: '2021-06-18', keywords: ['北海道ツーリング', 'SR400', '大洗', 'さんふらわあ', '苫小牧', '札幌', 'フェリー'] },
    { file: 'hokkaido-sr400-day2.html',   title: '札幌から石狩経由オロロンラインで稚内へ【SR400北海道ツーリング記録②】',                                                           category: 'bike',       tag: '北海道',           img: '../images/hokkaido/オロロンライン.jpg',                                                                                    date: '2021-06-20', keywords: ['北海道ツーリング', 'SR400', '札幌', '石狩', 'オロロンライン', '稚内', '海岸線'] },
    { file: 'hokkaido-sr400-day3.html',   title: '宗谷岬・白い道・エサヌカ線｜紋別の夜にヒグマと遭遇【SR400北海道ツーリング記録③】',                                              category: 'bike',       tag: '北海道',           img: '../images/hokkaido/soya-misaki-sr400-self.jpg',                                                                            date: '2021-06-21', keywords: ['北海道ツーリング', 'SR400', '宗谷岬', '白い道', 'エサヌカ線', '紋別', 'ヒグマ', '熊', 'クマ'] },
    { file: 'hokkaido-sr400-day4.html',   title: '紋別から美瑛へ｜青い池とパッチワークの路【SR400北海道ツーリング記録④】',                                                         category: 'bike',       tag: '北海道',           img: '../images/hokkaido/aoi-ike-pano.jpg',                                                                                       date: '2021-06-22', keywords: ['北海道ツーリング', 'SR400', '紋別', '美瑛', '青い池', 'パッチワークの路', '富良野'] },
    { file: 'hokkaido-sr400-day5.html',   title: '富良野ファーム富田から苫小牧｜フェリーで大洗へ【SR400北海道ツーリング記録⑤】',                                                   category: 'bike',       tag: '北海道',           img: '../images/hokkaido/furano-lavender.jpg',                                                                                    date: '2021-06-23', keywords: ['北海道ツーリング', 'SR400', '富良野', 'ファーム富田', 'ラベンダー', '苫小牧', '大洗', 'フェリー'] },
    { file: 'hokkaido-bear-spray.html',   title: '知床ツーリングで実感した熊撃退スプレーの必要性｜UDAP 12HP【装備編③】',                                                            category: 'bike',       tag: '北海道',           img: '../images/og/hokkaido-bear-spray.jpg',                                                                                      date: '2026-04-26', keywords: ['北海道', '知床', '熊', 'ヒグマ', 'クマ', '撃退スプレー', 'UDAP', '12HP', '装備', 'ツーリング', 'バイク'] },
    { file: 'hokkaido-gear-list.html',    title: '北海道ツーリング装備リスト｜2,400km走って分かった必須アイテム【装備編①】',                                                                  category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250819_070951847_iOS.jpg',                                                                      date: '2026-04-26', keywords: ['北海道', 'ツーリング', '装備', 'ギア', '必須アイテム', 'リスト'] },
    { file: 'hokkaido-routes.html',       title: '北海道ツーリング3回の記録｜SR400・車・XSR900で走ったルートと宿まとめ',                                                          category: 'bike',       tag: '北海道',           img: '../images/hokkaido/エサヌカ線.jpg',                                                                                          date: '2026-04-26', keywords: ['北海道', 'ツーリング', 'ルート', '宿', 'SR400', 'XSR900', 'まとめ'] },
    { file: 'taiwan.html',                title: '台湾旅行記｜基隆の夕暮れと十分のランタン上げが想像以上によかった',                   category: 'other',      tag: '台湾',             img: '../images/taiwan/z50_0939_dxo.jpg',                                                                                      date: '2025-09-01', keywords: ['台湾', '旅行', '基隆', '十分', 'ランタン', '夕暮れ'] },
    { file: 'costa-rica-intro.html',       title: 'コスタリカとはどんな国？｜自然・治安・暮らしを元在住者が紹介【コスタリカ滞在記①】',                               category: 'costa-rica', tag: 'コスタリカ',       img: '../images/costa-rica-2025/cr-1.jpg',                                                                                     date: '2018-01-30', keywords: ['コスタリカ', 'Costa Rica', '中米', '中南米', '自然', '治安', '暮らし', '元在住者'] },
    { file: 'costa-rica-irazu.html',       title: 'イラス火山の行き方と見どころ｜火口湖が見えなかった日【コスタリカ滞在記②】',                         category: 'costa-rica', tag: 'コスタリカ',       img: '../images/costa-rica-irazu/irazu-crater-view.jpg',                                                                       date: '2013-11-07', keywords: ['コスタリカ', 'イラス火山', '火口湖', 'クレーター', '中米', '火山'] },
    { file: 'costa-rica-christmas.html',   title: 'コスタリカのクリスマスと年越し｜タマル・爆竹・光の祭典【コスタリカ滞在記③】',                           category: 'costa-rica', tag: 'コスタリカ',       img: 'https://static.wixstatic.com/media/949ec9_bd4831b3aa4f4502a43029245d5fddc4~mv2_d_2800_2800_s_4_2.jpg',                  date: '2018-02-02', keywords: ['コスタリカ', 'クリスマス', '年越し', 'タマル', '爆竹', '光の祭典'] },
    { file: 'costa-rica-color-run.html',   title: 'コスタリカ日本人学校とThe Color Run｜サンホセで見た子どもたちと祭り【コスタリカ滞在記④】',                           category: 'costa-rica', tag: 'コスタリカ',       img: 'https://static.wixstatic.com/media/949ec9_6a5dbafe9b2a402589c1c87b64e296ba~mv2.png',                                    date: '2019-02-12', keywords: ['コスタリカ', '日本人学校', 'Color Run', 'カラーラン', 'サンホセ', '子ども', '祭り'] },
    { file: 'costa-rica-semana-santa.html', title: 'マヌエル・アントニオ国立公園へ｜セマナ・サンタのコスタリカ旅行【コスタリカ滞在記⑤】',               category: 'costa-rica', tag: 'コスタリカ',       img: '../images/costa-rica/manuel-antonio-animals.avif',                                                                       date: '2019-02-05', keywords: ['コスタリカ', 'マヌエル・アントニオ', '国立公園', 'セマナ・サンタ', 'イースター', '動物'] },
    { file: 'costa-rica-food.html',        title: 'コスタリカ・中米料理まとめ｜ガジョピント、セビーチェ、ライス＆ビーンズ【コスタリカ滞在記⑥】',                                           category: 'costa-rica', tag: 'コスタリカ',       img: 'https://static.wixstatic.com/media/949ec9_ba55d298fd444594b32692749af90ed2~mv2.png',                                    date: '2019-02-12', keywords: ['コスタリカ', '中米料理', 'ガジョピント', 'セビーチェ', 'ライス&ビーンズ', 'グルメ', '料理'] },
    { file: 'costa-rica-work.html',        title: 'コスタリカで理学療法士として働いた話｜簡易装具で歩けるようになった患者【コスタリカ滞在記⑦】', category: 'costa-rica', tag: 'コスタリカ',       img: 'https://static.wixstatic.com/media/949ec9_3ddc83f695764babb8d3abf036ffa77e~mv2.jpg',                                    date: '2018-08-09', keywords: ['コスタリカ', '理学療法士', 'PT', '仕事', '装具', '補装具', 'リハビリ'] },
    { file: 'costa-rica-cano-negro.html',  title: 'カニョネグロとモンテベルデ旅行記｜野生動物を探す年末年始【コスタリカ滞在記⑧】',     category: 'costa-rica', tag: 'コスタリカ',       img: '../images/costa-rica-cano-negro/monteverde-motmot.jpg',                                                                   date: '2014-12-25', keywords: ['コスタリカ', 'カニョネグロ', 'モンテベルデ', '野生動物', 'ボートツアー', '年末年始'] },
    { file: 'costa-rica-aribada.html',     title: 'アリバダを見にオスティオナルへ｜ヒメウミガメ集団産卵に間に合わなかった話【コスタリカ滞在記⑨】',                 category: 'costa-rica', tag: 'コスタリカ',       img: '../images/costa-rica-aribada/aribada-beach.jpg',                                                                         date: '2015-09-01', keywords: ['コスタリカ', 'アリバダ', 'オスティオナル', 'ヒメウミガメ', '集団産卵', '海亀', 'ウミガメ'] },
    { file: 'nicaragua-ometepe-1.html',   title: 'コスタリカからニカラグアへ国境越え｜TICA BUSでオメテペ島へ【ニカラグア旅行記①】',  category: 'nicaragua',  tag: 'ニカラグア',       img: 'https://static.wixstatic.com/media/949ec9_019bd4603cf949559dd74edbb0af66f0~mv2.jpg',                                    date: '2016-11-06', keywords: ['ニカラグア', 'コスタリカ', '国境越え', 'TICA BUS', 'オメテペ島'] },
    { file: 'nicaragua-ometepe-2.html',   title: 'オメテペ島観光を1日で巡る｜オホ・デ・アグアと火山島の見どころ【ニカラグア旅行記②】',   category: 'nicaragua',  tag: 'ニカラグア',       img: 'https://static.wixstatic.com/media/949ec9_ef3f551a51dd4c5aa071e586251d053c~mv2.jpg',                                    date: '2016-11-08', keywords: ['ニカラグア', 'オメテペ島', 'オホ・デ・アグア', '火山島', '観光'] },
    { file: 'nicaragua-granada.html',     title: 'グラナダ観光と革製品探し｜ニカラグアの植民地都市を歩く【ニカラグア旅行記③】',         category: 'nicaragua',  tag: 'ニカラグア',       img: 'https://static.wixstatic.com/media/949ec9_fb403e7af29a471c8b1254216f87e047~mv2_d_2048_1366_s_2.jpg',                  date: '2016-11-16', keywords: ['ニカラグア', 'グラナダ', '革製品', '植民地', '街歩き'] },
    { file: 'nicaragua-managua.html',     title: 'マナグア観光と友人との再会｜ニカラグアの首都で過ごした一日【ニカラグア旅行記④】',       category: 'nicaragua',  tag: 'ニカラグア',       img: 'https://static.wixstatic.com/media/949ec9_f1a030e4b47244219104f6bf529c572b~mv2.jpg',                                    date: '2018-06-13', keywords: ['ニカラグア', 'マナグア', '首都', '友人', '街歩き'] },
    { file: 'nicaragua-leon.html',        title: 'レオン観光｜革命の記憶とルベン・ダリオの街を歩く【ニカラグア旅行記⑤】',               category: 'nicaragua',  tag: 'ニカラグア',       img: 'https://static.wixstatic.com/media/949ec9_8875da9d3c0a4cf5a82475a6fc11b57a~mv2.jpg',                                    date: '2018-06-17', keywords: ['ニカラグア', 'レオン', '革命', 'ルベン・ダリオ', '街歩き'] },
    { file: 'nicaragua-flor-de-cana.html', title: 'フロール・デ・カーニャ工場見学｜ニカラグアのラム酒を味わう【ニカラグア旅行記⑥】',     category: 'nicaragua',  tag: 'ニカラグア',       img: 'https://static.wixstatic.com/media/949ec9_2abdad5c98df48c09ea644159fd8cd96~mv2_d_4608_3072_s_4_2.jpg',                  date: '2016-09-07', keywords: ['ニカラグア', 'フロール・デ・カーニャ', 'ラム酒', '工場見学', 'Flor de Caña'] },
    { file: 'el-salvador-ruins.html',     title: 'ホヤ・デ・セレンとタスマル遺跡へ｜エルサルバドルの世界遺産とマヤ遺跡【エルサルバドル旅行記①】',                     category: 'other',      tag: 'エルサルバドル',   img: '../images/el-salvador-ruins/ruins-1.jpg',                                                                                date: '2014-08-31', keywords: ['エルサルバドル', 'ホヤ・デ・セレン', 'タスマル', '遺跡', 'マヤ', '世界遺産'] },
    { file: 'el-salvador-volcan.html',    title: 'サンタ・アナ火山登山｜警察エスコート付きで火口湖を見に行った話【エルサルバドル旅行記②】',           category: 'other',      tag: 'エルサルバドル',   img: '../images/el-salvador-volcan/volcan-1.jpg',                                                                              date: '2014-09-02', keywords: ['エルサルバドル', 'サンタ・アナ', '火山', '登山', '火口湖', '警察エスコート'] },
    { file: 'mexico-zocalo.html',         title: 'メキシコシティ歴史地区観光｜ソカロ・テンプロマヨール・大聖堂を歩く【メキシコ旅行記①】',                             category: 'mexico',     tag: 'メキシコ',         img: '../images/mexico/zocalo-catedral.jpg',                                                                                   date: '2026-02-22', keywords: ['メキシコ', 'メキシコシティ', 'ソカロ', 'テンプロ・マヨール', '大聖堂', '歴史地区'] },
    { file: 'mexico-guadalupe.html',      title: 'グアダルーペ大聖堂の見どころ｜テペヤックの丘と奇跡のマント【メキシコ旅行記②】',                                     category: 'mexico',     tag: 'メキシコ',         img: '../images/mexico/guadalupe-aerial.jpg',                                                                                  date: '2026-02-21', keywords: ['メキシコ', 'メキシコシティ', 'グアダルーペ', '大聖堂', 'テペヤック', '奇跡のマント'] },
    { file: 'mexico-walk.html',           title: 'メキシコシティ街歩き｜革命記念塔・朝食・ストリートアートを巡る【メキシコ旅行記③】',                                     category: 'mexico',     tag: 'メキシコ',         img: '../images/mexico/revolucion-monument.jpg',                                                                               date: '2026-02-21', keywords: ['メキシコ', 'メキシコシティ', '街歩き', '革命記念塔', '朝食', 'ストリートアート'] },
    { file: 'mexico-walmart.html',        title: 'メキシコ土産はウォルマートが穴場｜サルサ・コーヒー・チョコレート購入記【メキシコ旅行記④】',                           category: 'mexico',     tag: 'メキシコ',         img: '../images/mexico/walmart-salsa.jpg',                                                                                     date: '2026-02-22', keywords: ['メキシコ', 'ウォルマート', 'お土産', 'サルサ', 'コーヒー', 'チョコレート', 'ショッピング'] },
    { file: 'mexico-anthropology.html',   title: '国立人類学博物館で巡る古代メキシコ｜太陽の石とコアトリクエ・オルメカ巨頭【メキシコ周遊記①】',                          category: 'mexico',     tag: 'メキシコ',         img: '../images/mexico/anthropology-aztec-hall.jpg',                                                                           date: '2015-06-20', keywords: ['メキシコ', 'メキシコシティ', '人類学博物館', 'アステカ', 'オルメカ', 'コアトリクエ', '太陽の石', '古代文明'] },
    { file: 'mexico-guanajuato.html',     title: '「宝石箱の街」グアナファト｜ピピラ像の夜景と接吻の小道、ミイラ博物館の真実【メキシコ周遊記②】',                          category: 'mexico',     tag: 'メキシコ',         img: '../images/mexico/guanajuato-night.jpg',                                                                                  date: '2015-06-21', keywords: ['メキシコ', 'グアナファト', '世界遺産', 'ピピラ像', '接吻の小道', 'ミイラ博物館', '夜景', '宝石箱'] },
    { file: 'mexico-teotihuacan.html',    title: 'テオティワカン遺跡を歩く｜太陽のピラミッド・月のピラミッド・羽毛の蛇神殿【メキシコ周遊記③】',                                category: 'mexico',     tag: 'メキシコ',         img: '../images/mexico/teotihuacan-sun-pyramid.jpg',                                                                            date: '2015-06-22', keywords: ['メキシコ', 'テオティワカン', '太陽のピラミッド', '月のピラミッド', '羽毛の蛇神殿', '死者の道', '古代文明', '周遊記'] },
    { file: 'mexico-palenque.html',       title: 'ジャングルに眠るマヤ遺跡パレンケ｜碑文の神殿・パカル王の墓・葉十字神殿群【メキシコ周遊記④】',                                category: 'mexico',     tag: 'メキシコ',         img: '../images/mexico/palenque-inscriptions-front.jpg',                                                                       date: '2015-06-25', keywords: ['メキシコ', 'チアパス', 'パレンケ', 'マヤ文明', 'パカル王', '碑文の神殿', '世界遺産', '古代文明'] },
    { file: 'touring-camp-gear.html',     title: 'バイクソロキャンプ道具まとめ｜テント・シュラフ・マット選び【キャンプ道具編①】',                       category: 'camp',       tag: 'キャンプ・ギア',   img: '../images/og/touring-camp-gear.jpg',                                                                                       date: '2017-11-12', keywords: ['バイク', 'ソロキャンプ', 'キャンプ道具', 'テント', 'シュラフ', 'マット', 'ギア'] },
    { file: 'camp-mori-makiba.html',      title: '森のまきばオートキャンプ場レビュー｜冬のソロキャンプと料金・雰囲気',                               category: 'camp',       tag: 'キャンプ',         img: 'https://static.wixstatic.com/media/949ec9_be02da1f1cce47dfa15fb7184f2e8dd6~mv2_d_4032_3024_s_4_2.jpg',                  date: '2018-12-15', keywords: ['森のまきば', 'オートキャンプ場', '千葉', 'ソロキャンプ', '冬キャンプ', 'レビュー'] },
    { file: 'atsukan.html',               title: '家で熱燗を楽しむ日本酒レビュー｜萬寿鏡F60と八海山雪室貯蔵三年',                                       category: 'other',      tag: '酒・グルメ',       img: 'https://static.wixstatic.com/media/949ec9_69fcb4358adc4328a919ec0cfc491f98~mv2_d_2987_3938_s_4_2.jpg',                  date: '2017-01-10', keywords: ['熱燗', '日本酒', '萬寿鏡', '八海山', '雪室貯蔵', 'グルメ', '酒'] },
    { file: 'power-beam.html',            title: 'SR400の振動対策にパワービームを装着｜長距離ツーリングでの変化をレビュー',                                       category: 'bike',       tag: 'バイク・ギア',     img: 'https://static.wixstatic.com/media/949ec9_c07a3465b14f4301835b4585c13ca9b3~mv2_d_4032_3024_s_4_2.jpg',                  date: '2018-09-19', keywords: ['SR400', 'パワービーム', '振動対策', 'バイクパーツ', 'ギア', 'カスタム'] },
    { file: 'spanish-dictionary.html',    title: 'スペイン語辞書おすすめ比較｜紙辞書・電子辞書・アプリを中米経験者が選ぶ',                           category: 'other',      tag: 'スペイン語',       img: 'https://static.wixstatic.com/media/949ec9_316ae78b6611491fad1cb3d780461968~mv2.jpg',                                    date: '2016-10-12', keywords: ['スペイン語', '辞書', '紙辞書', '電子辞書', 'アプリ', '中米', '語学'] },
    { file: 'bandai-azuma.html',          title: '磐梯吾妻スカイラインツーリング｜火山地帯を走る福島の絶景ルート',                               category: 'bike',       tag: 'ツーリング',       img: '../images/bandai/IMG_3857.jpg',                                                                                          date: '2018-10-01', keywords: ['磐梯吾妻スカイライン', 'ツーリング', '福島', '火山', '絶景', 'SR400'] },
    { file: 'five-color-lake.html',       title: '五色沼観光｜福島・裏磐梯でエメラルドグリーンの湖沼群を歩く',                                         category: 'bike',       tag: '旅',               img: '../images/five-color-lake/IMG_8015.jpg',                                                                                 date: '2018-10-02', keywords: ['五色沼', '福島', '裏磐梯', '観光', 'エメラルドグリーン', '湖沼'] },
    { file: 'hokkaido-car-day1.html',     title: '青森から新幹線で函館へ｜夜の街を歩く【北海道車旅①】',                                                                          category: 'bike',       tag: '北海道',           img: '../images/hokkaido-car/hakodate-night-view-2022.jpg',                                                                       date: '2022-08-25', keywords: ['北海道車旅', '青森', '新幹線', '函館', '夜景'] },
    { file: 'hokkaido-car-day2.html',     title: '羊蹄山・ニッカ余市蒸溜所・小樽運河を巡る【北海道車旅②】',                                                                      category: 'bike',       tag: '北海道',           img: '../images/hokkaido-car/mt-yotei.jpg',                                                                                       date: '2022-08-26', keywords: ['北海道車旅', '羊蹄山', 'ニッカ', '余市', '蒸溜所', '小樽運河'] },
    { file: 'hokkaido-car-day3.html',     title: '積丹半島ドライブ｜美国の黄金岬・神威岬・清寿司のウニイクラ丼【北海道車旅③】',                                                category: 'bike',       tag: '北海道',           img: '../images/hokkaido-car/kamui-misaki-pano.jpg',                                                                              date: '2022-08-27', keywords: ['北海道車旅', '積丹半島', '美国', '黄金岬', '神威岬', '清寿司', 'ウニ', 'イクラ', '海鮮'] },
    { file: 'hokkaido-car-day4.html',     title: '函館朝市・五稜郭・北海道第一歩の地碑【北海道車旅④】',                                                                          category: 'bike',       tag: '北海道',           img: '../images/hokkaido-car/goryokaku.jpg',                                                                                      date: '2022-08-28', keywords: ['北海道車旅', '函館朝市', '五稜郭', '北海道第一歩の地'] },
    { file: 'touring-chiba-xsr900.html',  title: 'XSR900千葉ソロツーリング｜笠森観音と房総の山道を走る',                               category: 'bike',       tag: 'ツーリング',       img: '../images/touring-chiba2/IMG_2388.jpg',                                                                                  date: '2026-04-01', keywords: ['XSR900', '千葉', 'ツーリング', 'ソロ', '笠森観音', '房総', '山道'] },
    { file: 'chile-1.html',               title: 'サンティアゴ市内観光｜チリ最高裁・美術館・歴史地区を歩く【チリ旅行記①】',                                 category: 'other',      tag: 'チリ',             img: '../images/chile/20251012_143804099_iOS.jpg',                                                                              date: '2025-10-12', keywords: ['チリ', 'サンティアゴ', '観光', '最高裁', '美術館', '歴史地区'] },
    { file: 'chile-2.html',               title: 'ロス・ドミニコス工芸市場へ｜サンティアゴで民芸品と白い教会を巡る【チリ旅行記②】',                                   category: 'other',      tag: 'チリ',             img: '../images/chile/20251014_205137977_iOS.jpg',                                                                              date: '2025-10-14', keywords: ['チリ', 'サンティアゴ', 'ロス・ドミニコス', '工芸市場', '民芸品', '教会'] },
    { file: 'chile-3.html',               title: 'サンティアゴ最終日｜パルタ・レイナとクリスマス前の街歩き【チリ旅行記③】',                                   category: 'other',      tag: 'チリ',             img: '../images/chile/20251016_170946020_iOS.jpg',                                                                              date: '2025-10-16', keywords: ['チリ', 'サンティアゴ', 'パルタ・レイナ', 'クリスマス', '街歩き'] },
    { file: 'belize-1.html',              title: 'ベリーズシティ到着｜夜明けのカリブ海とアジア系スーパー散策【ベリーズ旅行記①】',                 category: 'other',      tag: 'ベリーズ',         img: '../images/belize/20251018_213429265_iOS.jpg',                                                                             date: '2025-10-18', keywords: ['ベリーズ', 'ベリーズシティ', 'カリブ海', 'アジア系スーパー', '到着'] },
    { file: 'belize-2.html',              title: 'キーカーカー島とグレート・ブルーホール遊覧飛行｜ベリーズのカリブ海を空から見る【ベリーズ旅行記②】',             category: 'other',      tag: 'ベリーズ',         img: '../images/belize/20251019_213939041_iOS.jpg',                                                                             date: '2025-10-19', keywords: ['ベリーズ', 'キーカーカー', 'グレート・ブルーホール', '遊覧飛行', 'カリブ海', 'ブルーホール'] },
    { file: 'belize-3.html',              title: 'ベリーズシティ街歩き｜スウィング・ブリッジと最終日の過ごし方【ベリーズ旅行記③】',                       category: 'other',      tag: 'ベリーズ',         img: '../images/belize/20251020_144751630_iOS.jpg',                                                                             date: '2025-10-20', keywords: ['ベリーズ', 'ベリーズシティ', 'スウィング・ブリッジ', '街歩き', '最終日'] },
    { file: 'zao-ginzan.html',            title: '蔵王と銀山温泉1泊2日｜御釜・大露天風呂・大正ロマンの夜景',                                     category: 'other',      tag: '東北',             img: '../images/zao-ginzan/20250628_133653099_iOS.jpg',                                                                         date: '2025-06-28', keywords: ['蔵王', '銀山温泉', '御釜', '大露天風呂', '大正ロマン', '山形', '温泉', '東北'] },
    { file: 'himawari-tsunan.html',       title: '新潟夏旅2日間｜津南ひまわり畑と長岡花火大会を巡る',                           category: 'other',      tag: '新潟',             img: '../images/himawari/20250802_011958175_iOS_1.jpg',                                                                         date: '2025-08-02', keywords: ['新潟', '津南', 'ひまわり畑', '長岡花火', '夏旅', '花火大会'] },
    { file: 'hokkaido-xsr900-day1.html',  title: '大洗からさんふらわあで苫小牧へ【XSR900北海道ツーリング記録①】',                         category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250819_070951847_iOS.jpg',                                                                    date: '2025-08-19', keywords: ['XSR900', '北海道ツーリング', '大洗', 'さんふらわあ', '苫小牧', 'フェリー'] },
    { file: 'hokkaido-xsr900-day2.html',  title: '苫小牧から帯広へ｜二風谷アイヌ文化博物館と十勝豚丼を巡る【XSR900北海道ツーリング記録②】',                          category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250820_054937983_iOS.jpg',                                                                    date: '2025-08-20', keywords: ['XSR900', '北海道ツーリング', '苫小牧', '帯広', '二風谷', 'アイヌ', '十勝豚丼'] },
    { file: 'hokkaido-xsr900-day3.html',  title: '厚岸蒸留所と根室の海鮮を楽しむ東北海道ルート【XSR900北海道ツーリング記録③】',                                category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250821_010411011_iOS.jpg',                                                                    date: '2025-08-21', keywords: ['XSR900', '北海道ツーリング', '厚岸蒸留所', '根室', '海鮮', 'ウイスキー', '道東'] },
    { file: 'hokkaido-xsr900-day4.html',  title: '納沙布岬から知床五湖へ走る道東ツーリング【XSR900北海道ツーリング記録④】',                                    category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250822_073520142_iOS.jpg',                                                                    date: '2025-08-22', keywords: ['XSR900', '北海道ツーリング', '納沙布岬', '知床五湖', '道東', '天に続く道'] },
    { file: 'hokkaido-xsr900-day5.html',  title: '神の子池・美幌峠・網走監獄を巡る【XSR900北海道ツーリング記録⑤】',                            category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250823_022248708_iOS.jpg',                                                                    date: '2025-08-23', keywords: ['XSR900', '北海道ツーリング', '神の子池', '美幌峠', '網走監獄'] },
    { file: 'hokkaido-xsr900-day6.html',  title: '枝幸で財布を落としてAirTagに救われた話【XSR900北海道ツーリング記録⑥】',                                category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250824_040949567_iOS.jpg',                                                                    date: '2025-08-24', keywords: ['XSR900', '北海道ツーリング', '枝幸', '財布', '紛失', 'AirTag'] },
    { file: 'hokkaido-xsr900-day7.html',  title: 'オロロンラインを稚内から旭川へ走る【XSR900北海道ツーリング記録⑦】',                               category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250825_110201838_iOS.jpg',                                                                    date: '2025-08-25', keywords: ['XSR900', '北海道ツーリング', 'オロロンライン', '稚内', '旭川'] },
    { file: 'hokkaido-xsr900-day8.html',  title: '美瑛の青い池・白ひげの滝から苫小牧へ【XSR900北海道ツーリング記録⑧】',                        category: 'bike',       tag: '北海道',           img: '../images/hokkaido-xsr900/20250826_002032526_iOS.jpg',                                                                    date: '2025-08-26', keywords: ['XSR900', '北海道ツーリング', '美瑛', '青い池', '白ひげの滝', '苫小牧'] },
    { file: 'panama-1.html',              title: 'パナマ・ビエホ観光｜500年前の廃墟とスペイン植民地時代の歴史【パナマ旅行記①】',                         category: 'other',      tag: 'パナマ',           img: '../images/panama/pv-1.jpg',                                                                                               date: '2025-01-10', keywords: ['パナマ', 'パナマ・ビエホ', '廃墟', 'スペイン植民地', '世界遺産'] },
    { file: 'panama.html',                title: 'カスコ・ビエホとマリスコス市場を歩く｜世界遺産の旧市街と魚市場【パナマ旅行記②】',           category: 'other',      tag: 'パナマ',           img: '../images/panama/panama-1.jpg',                                                                                          date: '2025-01-11', keywords: ['パナマ', 'カスコ・ビエホ', 'マリスコス市場', '世界遺産', '旧市街', '魚市場'] },
    { file: 'panama-3.html',              title: 'ミラフローレス閘門見学｜パナマ運河で巨大船が通る瞬間を見た【パナマ旅行記③】',             category: 'other',      tag: 'パナマ',           img: '../images/panama/canal-1.jpg',                                                                                           date: '2025-01-12', keywords: ['パナマ', 'ミラフローレス', '閘門', 'パナマ運河', '巨大船'] },
    { file: 'costa-rica-2025.html',       title: 'コスタリカ10年ぶり再訪｜変わったサンホセと変わらないピルセンの味',             category: 'costa-rica', tag: 'コスタリカ',       img: '../images/costa-rica-2025/cr-5.jpg',                                                                                     date: '2025-01-15', keywords: ['コスタリカ', '10年ぶり', '再訪', 'サンホセ', 'ピルセン', 'ビール'] },
    { file: 'noto-touring.html',          title: '能登半島ツーリング記録｜総持寺祖院と金箔刺身の宿ごはん',                               category: 'bike',       tag: 'ツーリング',       img: '../images/noto/noto-1.jpg',                                                                                              date: '2022-08-01', keywords: ['能登半島', 'ツーリング', '総持寺祖院', '金箔', '刺身', '石川'] },
    { file: 'irako.html',                 title: '伊良湖岬ひとり旅｜年末の海辺と強風の愛知散歩',                                                   category: 'bike',       tag: 'ツーリング',       img: '../images/irako/lighthouse.jpg',                                                                                         date: '2023-12-31', keywords: ['伊良湖岬', 'ひとり旅', '愛知', '年末', '海辺'] },
    { file: 'chiba-chibanians.html',      title: 'チバニアン観光と千葉ツーリング｜地層見学・猪遭遇・バイクトラブル',                 category: 'bike',       tag: 'ツーリング',       img: '../images/chiba-chibanians/chiba-cliff.jpg',                                                                             date: '2024-05-01', keywords: ['チバニアン', '千葉', 'ツーリング', '地層', '猪', 'バイクトラブル'] },
    { file: 'toro-daishi.html',           title: '燈籠坂大師の切通しトンネルへ｜千葉の写真映えスポットをXSR900で再訪',                     category: 'bike',       tag: 'ツーリング',       img: '../images/toro-daishi/toro-1.jpg',                                                                                       date: '2024-03-01', keywords: ['燈籠坂大師', '切通しトンネル', '千葉', 'XSR900', '写真映え'] },
    { file: 'izu-touring.html',           title: '伊豆半島1泊2日ツーリング｜芦ノ湖スカイラインと西伊豆ルート',                               category: 'bike',       tag: 'ツーリング',       img: '../images/izu-touring/sea.jpg',                                                                                          date: '2023-06-16', keywords: ['伊豆半島', 'ツーリング', '芦ノ湖スカイライン', '西伊豆', '静岡'] },
    { file: 'motorcycle-show-2026.html',  title: '東京モーターサイクルショー2026感想｜気になったバイクとサイドバッグ',                         category: 'bike',       tag: 'バイク',           img: '../images/motorcycle-show/cbr400r.jpg',                                                                                  date: '2026-03-28', keywords: ['モーターサイクルショー', '2026', '東京', 'バイク', 'サイドバッグ'] },
    { file: 'long-haul-flight-tips.html', title: '長距離フライトの過ごし方｜エコノミーでも少し快適に過ごす工夫【装備編②】',                                                       category: 'other',      tag: '海外旅行',         img: '../images/flight/jal-gate.jpg',                                                                                          date: '2026-04-29', keywords: ['長距離フライト', '海外旅行', '機内', 'エコノミー', '持ち物', 'ネックピロー', 'イヤホン', '2ピン変換', 'AirFly', 'OOFOS', 'ガジェットポーチ'] }
  ];

  window.ARTICLES = ARTICLES;

  document.addEventListener('DOMContentLoaded', function () {
    initV2Header();
    initLangSwitcher();
    injectScrollLine();
    injectBackToTop();
    injectDarkModeToggle();
    injectLightbox();
    injectLazyLoading();
    injectTOC();
    injectShareButtons();
    injectSeriesNav();
    injectRelated();
    injectMapLinks();
    injectCopyCredit();
    injectSearch();
  });

  // ── Language switcher dropdown toggle ──────────────────────────
  function initLangSwitcher() {
    var triggers = document.querySelectorAll('.v2-lang-switcher .lang-trigger');
    if (!triggers.length) return;
    triggers.forEach(function (btn) {
      if (btn.dataset.langInit) return;
      btn.dataset.langInit = '1';
      btn.addEventListener('click', function (e) {
        e.stopPropagation();
        var parent = btn.parentElement;
        var willOpen = !parent.classList.contains('open');
        document.querySelectorAll('.v2-lang-switcher.open').forEach(function (el) {
          if (el !== parent) {
            el.classList.remove('open');
            var b = el.querySelector('.lang-trigger');
            if (b) b.setAttribute('aria-expanded', 'false');
          }
        });
        parent.classList.toggle('open', willOpen);
        btn.setAttribute('aria-expanded', willOpen ? 'true' : 'false');
      });
    });
    document.addEventListener('click', function (e) {
      if (e.target.closest('.v2-lang-switcher')) return;
      document.querySelectorAll('.v2-lang-switcher.open').forEach(function (el) {
        el.classList.remove('open');
        var b = el.querySelector('.lang-trigger');
        if (b) b.setAttribute('aria-expanded', 'false');
      });
    });
  }

  // ── V2 Header (hamburger + dropdown + scroll) ──────────────────
  function initV2Header() {
    var header = document.querySelector('.v2-header');
    if (!header || header.dataset.v2Init) return;
    header.dataset.v2Init = '1';

    var burger = header.querySelector('.v2-hamburger');
    if (burger) {
      burger.addEventListener('click', function () {
        header.classList.toggle('menu-open');
        if (!header.classList.contains('menu-open')) {
          header.querySelectorAll('.v2-dropdown.open').forEach(function (d) { d.classList.remove('open'); });
        }
      });
    }

    header.querySelectorAll('.v2-dropdown .dropdown-trigger').forEach(function (trigger) {
      trigger.addEventListener('click', function (e) {
        e.preventDefault();
        e.stopPropagation();
        header.querySelectorAll('.v2-dropdown.open').forEach(function (d) {
          if (d !== trigger.parentElement) d.classList.remove('open');
        });
        trigger.parentElement.classList.toggle('open');
      });
    });

    document.addEventListener('click', function (e) {
      if (!e.target.closest('.v2-dropdown')) {
        header.querySelectorAll('.v2-dropdown.open').forEach(function (d) { d.classList.remove('open'); });
      }
    });

    window.addEventListener('scroll', function () {
      if (window.scrollY > 80) header.classList.add('scrolled');
      else header.classList.remove('scrolled');
    });
  }

  // ── Search ─────────────────────────────────────────────────────
  function injectSearch() {
    var headerInner = document.querySelector('.header-inner, .v2-header-inner');
    if (!headerInner) return;

    var btn = document.createElement('button');
    btn.className = 'search-trigger';
    btn.setAttribute('aria-label', t('search'));
    btn.innerHTML = '<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>';
    headerInner.appendChild(btn);

    var overlay = document.createElement('div');
    overlay.className = 'search-overlay';
    overlay.innerHTML =
      '<button class="search-close">&#215;</button>' +
      '<div class="search-input-wrap">' +
        '<input type="text" class="search-input" placeholder="' + t('searchPlaceholder') + '" autocomplete="off" spellcheck="false"/>' +
      '</div>' +
      '<div class="search-results"></div>' +
      '<p class="search-hint">' + t('searchHint') + '</p>';
    document.body.appendChild(overlay);

    var input = overlay.querySelector('.search-input');
    var results = overlay.querySelector('.search-results');

    function openSearch() { overlay.classList.add('active'); setTimeout(function() { input.focus(); }, 50); }
    function closeSearch() { overlay.classList.remove('active'); input.value = ''; results.innerHTML = ''; }

    btn.addEventListener('click', openSearch);
    overlay.querySelector('.search-close').addEventListener('click', closeSearch);
    overlay.addEventListener('click', function(e) { if (e.target === overlay) closeSearch(); });
    document.addEventListener('keydown', function(e) {
      if (e.key === 'Escape') closeSearch();
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') { e.preventDefault(); openSearch(); }
    });

    // 検索クエリ・対象テキストの揺れ吸収:
    // - カタカナ → ひらがな
    // - 全角英数記号 → 半角
    // - 大文字 → 小文字
    function normalize(s) {
      if (!s) return '';
      return String(s)
        .replace(/[ァ-ヶ]/g, function(ch) { return String.fromCharCode(ch.charCodeAt(0) - 0x60); })
        .replace(/[！-～]/g, function(ch) { return String.fromCharCode(ch.charCodeAt(0) - 0xFEE0); })
        .replace(/　/g, ' ')
        .toLowerCase();
    }

    input.addEventListener('input', function() {
      var q = this.value.trim();
      if (!q) { results.innerHTML = ''; return; }
      var ql = normalize(q);
      var all = window.ARTICLES || [];
      var matches = all.filter(function(a) {
        // EN/ES では翻訳済み記事のみを検索対象にする
        if (LANG !== 'ja' && !isTranslated(a.file)) return false;
        var matchTitle = normalize(articleTitle(a.file));
        var matchTag = normalize(articleTag(a.file));
        if (matchTitle.indexOf(ql) !== -1) return true;
        if (matchTag.indexOf(ql) !== -1) return true;
        // JA データのキーワードも横断検索（地名などは EN/ES でも有効）
        if (a.keywords) {
          for (var i = 0; i < a.keywords.length; i++) {
            if (normalize(a.keywords[i]).indexOf(ql) !== -1) return true;
          }
        }
        return false;
      });
      if (!matches.length) {
        results.innerHTML = '<p class="search-empty">' + t('searchEmpty', { q: q }) + '</p>';
        return;
      }
      var pathname = location.pathname;
      var isArticlePage = pathname.indexOf('/articles/') !== -1;
      // ルートからの記事プレフィックス（例: 'articles/', 'articles/en/', 'articles/es/'）
      var articlePrefix = LANG === 'ja' ? 'articles/' : ('articles/' + LANG + '/');
      // 現在地から articlePrefix までの相対パス
      var base;
      if (LANG === 'ja') {
        base = isArticlePage ? '../' : '';
      } else {
        // /en/stories.html や /articles/en/foo.html から /articles/<lang>/ に到達する相対パス
        if (isArticlePage) {
          base = '../../';  // /articles/<lang>/foo.html → root → /articles/<lang>/
        } else {
          base = '../';  // /<lang>/stories.html → root → /articles/<lang>/
        }
      }
      results.innerHTML = matches.slice(0, 10).map(function(a) {
        var imgSrc;
        if (a.img.indexOf('http') === 0) {
          imgSrc = a.img;
        } else if (LANG !== 'ja' && isArticlePage) {
          // 記事は /articles/<lang>/foo.html。a.img は ../images/... → ../../images/... が必要
          imgSrc = a.img.indexOf('../') === 0 ? '../' + a.img : a.img;
        } else if (LANG !== 'ja' && !isArticlePage) {
          // /<lang>/stories.html。a.img は ../images/... 既に正しい
          imgSrc = a.img;
        } else {
          imgSrc = isArticlePage ? a.img : a.img.replace('../', '');
        }
        return '<a class="search-result-item" href="' + base + articlePrefix + a.file + '">' +
          '<div class="search-result-img" style="background-image:url(\'' + imgSrc + '\')"></div>' +
          '<div><div class="search-result-tag">' + articleTag(a.file) + '</div>' +
          '<div class="search-result-title">' + articleTitle(a.file) + '</div></div>' +
          '</a>';
      }).join('');
    });
  }

  // ── Scroll Line ────────────────────────────────────────────────
  function injectScrollLine() {
    if (document.querySelector('.scroll-line')) return;
    var line = document.createElement('div');
    line.className = 'scroll-line';
    document.body.prepend(line);
    window.addEventListener('scroll', function () {
      var max = document.body.scrollHeight - window.innerHeight;
      if (max > 0) line.style.width = (window.scrollY / max * 100) + '%';
    }, { passive: true });
  }

  // ── Back to Top ────────────────────────────────────────────────
  function injectBackToTop() {
    var btn = document.createElement('button');
    btn.className = 'back-to-top';
    btn.setAttribute('aria-label', t('backToTop'));
    btn.textContent = '↑';
    document.body.appendChild(btn);

    window.addEventListener('scroll', function () {
      btn.classList.toggle('visible', window.scrollY > 400);
    }, { passive: true });

    btn.addEventListener('click', function () {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });
  }

  // ── Dark Mode Toggle ───────────────────────────────────────────
  function injectDarkModeToggle() {
    var headerInner = document.querySelector('.header-inner, .v2-header-inner');
    if (!headerInner) return;

    var btn = document.createElement('button');
    btn.className = 'dark-toggle';
    btn.setAttribute('aria-label', t('darkMode'));
    btn.textContent = document.documentElement.getAttribute('data-theme') === 'dark' ? '☀' : '🌙';

    btn.addEventListener('click', function () {
      var nowDark = document.documentElement.getAttribute('data-theme') === 'dark';
      if (nowDark) {
        document.documentElement.removeAttribute('data-theme');
        localStorage.setItem('theme', 'light');
        btn.textContent = '🌙';
      } else {
        document.documentElement.setAttribute('data-theme', 'dark');
        localStorage.setItem('theme', 'dark');
        btn.textContent = '☀';
      }
    });

    headerInner.appendChild(btn);
  }

  // ── Lazy Loading ───────────────────────────────────────────────
  function injectLazyLoading() {
    document.querySelectorAll('img').forEach(function (img) {
      if (!img.hasAttribute('loading')) img.setAttribute('loading', 'lazy');
    });
  }

  // ── Lightbox ───────────────────────────────────────────────────
  function injectLightbox() {
    var overlay = document.createElement('div');
    overlay.className = 'lightbox-overlay';
    overlay.setAttribute('role', 'dialog');
    overlay.setAttribute('aria-modal', 'true');

    var closeBtn = document.createElement('button');
    closeBtn.className = 'lightbox-close';
    closeBtn.setAttribute('aria-label', t('lightboxClose'));
    closeBtn.textContent = '×';

    var lbImg = document.createElement('img');
    lbImg.className = 'lightbox-img';
    lbImg.alt = '';

    overlay.appendChild(closeBtn);
    overlay.appendChild(lbImg);
    document.body.appendChild(overlay);

    document.querySelectorAll('.article-body figure img').forEach(function (el) {
      el.style.cursor = 'zoom-in';
      el.addEventListener('click', function () {
        lbImg.src = el.src;
        lbImg.alt = el.alt;
        overlay.classList.add('active');
        document.body.style.overflow = 'hidden';
      });
    });

    function closeLightbox() {
      overlay.classList.remove('active');
      document.body.style.overflow = '';
    }
    closeBtn.addEventListener('click', closeLightbox);
    overlay.addEventListener('click', function (e) { if (e.target === overlay) closeLightbox(); });
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape') closeLightbox(); });
  }

  // ── Table of Contents ──────────────────────────────────────────
  function injectTOC() {
    var articleBody = document.querySelector('.article-body');
    if (!articleBody) return;
    var headings = articleBody.querySelectorAll('h2');
    if (headings.length < 3) return;

    headings.forEach(function (h, i) { if (!h.id) h.id = 'section-' + (i + 1); });

    var toc = document.createElement('div');
    toc.className = 'article-toc';

    var label = document.createElement('div');
    label.className = 'article-toc-label';
    label.textContent = t('tocLabel');

    var ol = document.createElement('ol');
    var tocLinks = [];
    headings.forEach(function (h) {
      var li = document.createElement('li');
      var a = document.createElement('a');
      a.href = '#' + h.id;
      a.textContent = h.textContent;
      a.addEventListener('click', function (e) {
        e.preventDefault();
        var headerH = (document.querySelector('header') || {}).offsetHeight || 64;
        var top = h.getBoundingClientRect().top + window.pageYOffset - headerH - 24;
        window.scrollTo({ top: top, behavior: 'smooth' });
        history.pushState(null, '', '#' + h.id);
      });
      tocLinks.push(a);
      li.appendChild(a);
      ol.appendChild(li);
    });

    toc.appendChild(label);
    toc.appendChild(ol);

    var backLink = articleBody.querySelector('.back-link');
    if (backLink) {
      backLink.parentNode.insertBefore(toc, backLink.nextSibling);
    } else {
      articleBody.insertBefore(toc, articleBody.firstChild);
    }

    if (!('IntersectionObserver' in window)) return;
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        tocLinks.forEach(function (a) { a.classList.remove('toc-active'); });
        var active = ol.querySelector('a[href="#' + entry.target.id + '"]');
        if (active) active.classList.add('toc-active');
      });
    }, { rootMargin: '-10% 0px -75% 0px' });

    headings.forEach(function (h) { observer.observe(h); });
  }

  // ── Share Buttons ──────────────────────────────────────────────
  function injectShareButtons() {
    var title = document.title.replace(' | Camino Libre', '');
    var url = location.href;
    var wrap = document.querySelector('.share-buttons');
    if (!wrap) return;

    var xLink = document.querySelector('.share-btn-x');
    if (xLink) xLink.href = 'https://x.com/intent/tweet?text=' + encodeURIComponent(title) + '&url=' + encodeURIComponent(url);

    var lineLink = document.querySelector('.share-btn-line');
    if (lineLink) lineLink.href = 'https://line.me/R/msg/text/?' + encodeURIComponent(title + '\n' + url);

    var copyBtn = document.querySelector('.share-btn-copy');
    if (copyBtn) {
      var copyLabel = copyBtn.querySelector('span');
      var originalText = copyLabel ? copyLabel.textContent : t('copy');
      copyBtn.addEventListener('click', function () {
        function done(msg) {
          if (copyLabel) {
            copyLabel.textContent = msg;
            setTimeout(function () { copyLabel.textContent = originalText; }, 2000);
          }
        }
        if (navigator.clipboard) {
          navigator.clipboard.writeText(url).then(function () { done(t('copied')); }).catch(function () { done(t('copyFailed')); });
        } else {
          try {
            var ta = document.createElement('textarea');
            ta.value = url; ta.style.cssText = 'position:fixed;opacity:0;';
            document.body.appendChild(ta); ta.select(); document.execCommand('copy');
            document.body.removeChild(ta); done(t('copied'));
          } catch (e) { done(t('copyFailed')); }
        }
      });
    }
  }

  // ── Series Navigation ──────────────────────────────────────────
  var SERIES = [
    { name: 'コスタリカ滞在記', catKey: 'costa-rica', articles: [
      { file: 'costa-rica-intro.html',        title: 'コスタリカとはどんな国？｜自然・治安・暮らしを元在住者が紹介【コスタリカ滞在記①】' },
      { file: 'costa-rica-irazu.html',        title: 'イラス火山の行き方と見どころ｜火口湖が見えなかった日【コスタリカ滞在記②】' },
      { file: 'costa-rica-christmas.html',    title: 'コスタリカのクリスマスと年越し｜タマル・爆竹・光の祭典【コスタリカ滞在記③】' },
      { file: 'costa-rica-color-run.html',    title: 'コスタリカ日本人学校とThe Color Run｜サンホセで見た子どもたちと祭り【コスタリカ滞在記④】' },
      { file: 'costa-rica-semana-santa.html', title: 'マヌエル・アントニオ国立公園へ｜セマナ・サンタのコスタリカ旅行【コスタリカ滞在記⑤】' },
      { file: 'costa-rica-food.html',         title: 'コスタリカ・中米料理まとめ｜ガジョピント、セビーチェ、ライス＆ビーンズ【コスタリカ滞在記⑥】' },
      { file: 'costa-rica-work.html',         title: 'コスタリカで理学療法士として働いた話｜簡易装具で歩けるようになった患者【コスタリカ滞在記⑦】' },
      { file: 'costa-rica-cano-negro.html',   title: 'カニョネグロとモンテベルデ旅行記｜野生動物を探す年末年始【コスタリカ滞在記⑧】' },
      { file: 'costa-rica-aribada.html',      title: 'アリバダを見にオスティオナルへ｜ヒメウミガメ集団産卵に間に合わなかった話【コスタリカ滞在記⑨】' }
    ]},
    { name: 'ニカラグア旅行記', catKey: 'nicaragua', articles: [
      { file: 'nicaragua-ometepe-1.html',    title: 'コスタリカからニカラグアへ国境越え｜TICA BUSでオメテペ島へ【ニカラグア旅行記①】' },
      { file: 'nicaragua-ometepe-2.html',    title: 'オメテペ島観光を1日で巡る｜オホ・デ・アグアと火山島の見どころ【ニカラグア旅行記②】' },
      { file: 'nicaragua-granada.html',      title: 'グラナダ観光と革製品探し｜ニカラグアの植民地都市を歩く【ニカラグア旅行記③】' },
      { file: 'nicaragua-managua.html',      title: 'マナグア観光と友人との再会｜ニカラグアの首都で過ごした一日【ニカラグア旅行記④】' },
      { file: 'nicaragua-leon.html',         title: 'レオン観光｜革命の記憶とルベン・ダリオの街を歩く【ニカラグア旅行記⑤】' },
      { file: 'nicaragua-flor-de-cana.html', title: 'フロール・デ・カーニャ工場見学｜ニカラグアのラム酒を味わう【ニカラグア旅行記⑥】' }
    ]},
    { name: 'メキシコ旅行記', catKey: 'mexico', articles: [
      { file: 'mexico-zocalo.html',    title: 'メキシコシティ歴史地区観光｜ソカロ・テンプロマヨール・大聖堂を歩く【メキシコ旅行記①】' },
      { file: 'mexico-guadalupe.html', title: 'グアダルーペ大聖堂の見どころ｜テペヤックの丘と奇跡のマント【メキシコ旅行記②】' },
      { file: 'mexico-walk.html',      title: 'メキシコシティ街歩き｜革命記念塔・朝食・ストリートアートを巡る【メキシコ旅行記③】' },
      { file: 'mexico-walmart.html',   title: 'メキシコ土産はウォルマートが穴場｜サルサ・コーヒー・チョコレート購入記【メキシコ旅行記④】' }
    ]},
    { name: 'メキシコ周遊記', catKey: 'mexico', articles: [
      { file: 'mexico-anthropology.html', title: '国立人類学博物館で巡る古代メキシコ｜太陽の石とコアトリクエ・オルメカ巨頭【メキシコ周遊記①】' },
      { file: 'mexico-guanajuato.html',   title: '「宝石箱の街」グアナファト｜ピピラ像の夜景と接吻の小道、ミイラ博物館の真実【メキシコ周遊記②】' },
      { file: 'mexico-teotihuacan.html',  title: 'テオティワカン遺跡を歩く｜太陽のピラミッド・月のピラミッド・羽毛の蛇神殿【メキシコ周遊記③】' },
      { file: 'mexico-palenque.html',     title: 'ジャングルに眠るマヤ遺跡パレンケ｜碑文の神殿・パカル王の墓・葉十字神殿群【メキシコ周遊記④】' }
    ]},
    { name: 'SR400北海道ツーリング記録', catKey: 'hokkaido', articles: [
      { file: 'hokkaido-sr400-day1.html', title: '大洗からさんふらわあで苫小牧｜初日は札幌へ【SR400北海道ツーリング記録①】' },
      { file: 'hokkaido-sr400-day2.html', title: '札幌から石狩経由オロロンラインで稚内へ【SR400北海道ツーリング記録②】' },
      { file: 'hokkaido-sr400-day3.html', title: '宗谷岬・白い道・エサヌカ線｜紋別の夜にヒグマと遭遇【SR400北海道ツーリング記録③】' },
      { file: 'hokkaido-sr400-day4.html', title: '紋別から美瑛へ｜青い池とパッチワークの路【SR400北海道ツーリング記録④】' },
      { file: 'hokkaido-sr400-day5.html', title: '富良野ファーム富田から苫小牧｜フェリーで大洗へ【SR400北海道ツーリング記録⑤】' }
    ]},
    { name: 'XSR900北海道ツーリング記録', catKey: 'hokkaido', articles: [
      { file: 'hokkaido-xsr900-day1.html', title: '大洗からさんふらわあで苫小牧へ【XSR900北海道ツーリング記録①】' },
      { file: 'hokkaido-xsr900-day2.html', title: '苫小牧から帯広へ｜二風谷アイヌ文化博物館と十勝豚丼を巡る【XSR900北海道ツーリング記録②】' },
      { file: 'hokkaido-xsr900-day3.html', title: '厚岸蒸留所と根室の海鮮を楽しむ東北海道ルート【XSR900北海道ツーリング記録③】' },
      { file: 'hokkaido-xsr900-day4.html', title: '納沙布岬から知床五湖へ走る道東ツーリング【XSR900北海道ツーリング記録④】' },
      { file: 'hokkaido-xsr900-day5.html', title: '神の子池・美幌峠・網走監獄を巡る【XSR900北海道ツーリング記録⑤】' },
      { file: 'hokkaido-xsr900-day6.html', title: '枝幸で財布を落としてAirTagに救われた話【XSR900北海道ツーリング記録⑥】' },
      { file: 'hokkaido-xsr900-day7.html', title: 'オロロンラインを稚内から旭川へ走る【XSR900北海道ツーリング記録⑦】' },
      { file: 'hokkaido-xsr900-day8.html', title: '美瑛の青い池・白ひげの滝から苫小牧へ【XSR900北海道ツーリング記録⑧】' }
    ]},
    { name: '北海道車旅', catKey: 'hokkaido', articles: [
      { file: 'hokkaido-car-day1.html', title: '青森から新幹線で函館へ｜夜の街を歩く【北海道車旅①】' },
      { file: 'hokkaido-car-day2.html', title: '羊蹄山・ニッカ余市蒸溜所・小樽運河を巡る【北海道車旅②】' },
      { file: 'hokkaido-car-day3.html', title: '積丹半島ドライブ｜美国の黄金岬・神威岬・清寿司のウニイクラ丼【北海道車旅③】' },
      { file: 'hokkaido-car-day4.html', title: '函館朝市・五稜郭・北海道第一歩の地碑【北海道車旅④】' }
    ]},
    { name: 'チリ旅行記', catKey: 'chile', articles: [
      { file: 'chile-1.html', title: 'サンティアゴ市内観光｜チリ最高裁・美術館・歴史地区を歩く【チリ旅行記①】' },
      { file: 'chile-2.html', title: 'ロス・ドミニコス工芸市場へ｜サンティアゴで民芸品と白い教会を巡る【チリ旅行記②】' },
      { file: 'chile-3.html', title: 'サンティアゴ最終日｜パルタ・レイナとクリスマス前の街歩き【チリ旅行記③】' }
    ]},
    { name: 'ベリーズ旅行記', catKey: 'belize', articles: [
      { file: 'belize-1.html', title: 'ベリーズシティ到着｜夜明けのカリブ海とアジア系スーパー散策【ベリーズ旅行記①】' },
      { file: 'belize-2.html', title: 'キーカーカー島とグレート・ブルーホール遊覧飛行｜ベリーズのカリブ海を空から見る【ベリーズ旅行記②】' },
      { file: 'belize-3.html', title: 'ベリーズシティ街歩き｜スウィング・ブリッジと最終日の過ごし方【ベリーズ旅行記③】' }
    ]},
    { name: 'エルサルバドル旅行記', catKey: 'el-salvador', articles: [
      { file: 'el-salvador-ruins.html',  title: 'ホヤ・デ・セレンとタスマル遺跡へ｜エルサルバドルの世界遺産とマヤ遺跡【エルサルバドル旅行記①】' },
      { file: 'el-salvador-volcan.html', title: 'サンタ・アナ火山登山｜警察エスコート付きで火口湖を見に行った話【エルサルバドル旅行記②】' }
    ]},
    { name: 'パナマ旅行記', catKey: 'panama', articles: [
      { file: 'panama-1.html', title: 'パナマ・ビエホ観光｜500年前の廃墟とスペイン植民地時代の歴史【パナマ旅行記①】' },
      { file: 'panama.html',   title: 'カスコ・ビエホとマリスコス市場を歩く｜世界遺産の旧市街と魚市場【パナマ旅行記②】' },
      { file: 'panama-3.html', title: 'ミラフローレス閘門見学｜パナマ運河で巨大船が通る瞬間を見た【パナマ旅行記③】' }
    ]},
    { name: '装備編', catKey: 'other', articles: [
      { file: 'hokkaido-gear-list.html',    title: '北海道ツーリング装備リスト｜2,400km走って分かった必須アイテム【装備編①】' },
      { file: 'long-haul-flight-tips.html', title: '長距離フライトの過ごし方｜エコノミーでも少し快適に過ごす工夫【装備編②】' },
      { file: 'hokkaido-bear-spray.html',   title: '知床ツーリングで実感した熊撃退スプレーの必要性｜UDAP 12HP【装備編③】' }
    ]}
  ];

  window.SERIES = SERIES;

  function injectSeriesNav() {
    var current = location.pathname.split('/').pop();
    if (current && !current.endsWith('.html')) current += '.html';
    var prev = null, next = null, seriesName = null, seriesCat = null;

    for (var g = 0; g < SERIES.length; g++) {
      var group = SERIES[g].articles;
      var idx = -1;
      for (var i = 0; i < group.length; i++) {
        if (group[i].file === current) { idx = i; break; }
      }
      if (idx === -1) continue;
      prev = idx > 0 ? group[idx - 1] : null;
      next = idx < group.length - 1 ? group[idx + 1] : null;
      seriesName = SERIES[g].name;
      seriesCat = SERIES[g].catKey;
      break;
    }

    if (!prev && !next) return;

    var nav = document.createElement('div');
    nav.className = 'article-series-nav';

    if (prev) {
      var prevLink = document.createElement('a');
      prevLink.className = 'series-nav-btn series-nav-prev';
      prevLink.href = prev.file;
      prevLink.innerHTML = '<span class="series-nav-label">' + t('previous') + '</span><span class="series-nav-title">' + articleTitle(prev.file) + '</span>';
      nav.appendChild(prevLink);
    } else {
      nav.appendChild(document.createElement('span'));
    }

    if (next) {
      var nextLink = document.createElement('a');
      nextLink.className = 'series-nav-btn series-nav-next';
      nextLink.href = next.file;
      nextLink.innerHTML = '<span class="series-nav-label">' + t('next') + '</span><span class="series-nav-title">' + articleTitle(next.file) + '</span>';
      nav.appendChild(nextLink);
    }

    if (seriesName && seriesCat) {
      var listLink = document.createElement('a');
      listLink.className = 'series-nav-list';
      listLink.href = storiesPath() + '?cat=' + seriesCat + '#articles';
      listLink.textContent = t('seriesViewAll', { series: seriesLabel(seriesName) });
      nav.appendChild(listLink);
    }

    var articleBody = document.querySelector('.article-body');
    if (!articleBody) return;
    var related = articleBody.querySelector('.related-section');
    var footer = articleBody.querySelector('footer');
    if (related) {
      articleBody.insertBefore(nav, related);
    } else if (footer) {
      articleBody.insertBefore(nav, footer);
    } else {
      articleBody.appendChild(nav);
    }
  }

  // ── Related Articles ───────────────────────────────────────────
  function injectRelated() {
    var articleBody = document.querySelector('.article-body');
    if (!articleBody) return;

    var current = location.pathname.split('/').pop();
    if (current && !current.endsWith('.html')) current += '.html';
    var currentArticle = null;
    for (var i = 0; i < ARTICLES.length; i++) {
      if (ARTICLES[i].file === current) { currentArticle = ARTICLES[i]; break; }
    }
    if (!currentArticle) return;

    function byDateDesc(a, b) { return new Date(b.date) - new Date(a.date); }

    // EN/ES では翻訳済み記事のみを related の候補にする
    var pool = ARTICLES.filter(function (a) {
      if (a.file === current) return false;
      return LANG === 'ja' || isTranslated(a.file);
    });
    var sameCat = pool.filter(function (a) { return a.category === currentArticle.category; }).sort(byDateDesc);
    var others = pool.filter(function (a) { return a.category !== currentArticle.category; }).sort(byDateDesc);

    var picks = sameCat.slice(0, 3);
    if (picks.length < 3) picks = picks.concat(others.slice(0, 3 - picks.length));
    if (picks.length === 0) return;

    var section = document.createElement('div');
    section.className = 'related-section';

    var label = document.createElement('div');
    label.className = 'related-label';
    label.textContent = t('relatedLabel');

    var grid = document.createElement('div');
    grid.className = 'related-grid';

    picks.forEach(function (a) {
      var card = document.createElement('a');
      card.className = 'related-card';
      card.href = a.file;

      var img = document.createElement('div');
      img.className = 'related-img';
      img.style.backgroundImage = 'url("' + a.img + '")';

      var tag = document.createElement('div');
      tag.className = 'related-tag';
      tag.textContent = articleTag(a.file);

      var title = document.createElement('div');
      title.className = 'related-title';
      title.textContent = articleTitle(a.file);

      card.appendChild(img);
      card.appendChild(tag);
      card.appendChild(title);
      grid.appendChild(card);
    });

    section.appendChild(label);
    section.appendChild(grid);
    var footer = articleBody.querySelector('footer');
    if (footer) {
      articleBody.insertBefore(section, footer);
    } else {
      articleBody.appendChild(section);
    }
  }

  // ── Map Links ──────────────────────────────────────────────────
  function injectMapLinks() {
    document.querySelectorAll('[data-map]').forEach(function (el) {
      var place = el.getAttribute('data-map');
      var link = document.createElement('a');
      link.className = 'map-link';
      link.href = 'https://www.google.com/maps/search/' + encodeURIComponent(place);
      link.target = '_blank';
      link.rel = 'noopener noreferrer';
      link.setAttribute('aria-label', t('mapAria', { place: place }));
      while (el.firstChild) link.appendChild(el.firstChild);
      el.appendChild(link);
    });
  }

  // ── Copy Credit ────────────────────────────────────────────────
  function injectCopyCredit() {
    var articleBody = document.querySelector('.article-body');
    if (!articleBody) return;

    var toast = document.createElement('div');
    toast.className = 'copy-toast';
    toast.textContent = t('toastQuoted');
    document.body.appendChild(toast);

    function showToast() {
      toast.classList.add('visible');
      setTimeout(function () { toast.classList.remove('visible'); }, 2500);
    }

    document.addEventListener('copy', function (e) {
      var selection = window.getSelection();
      if (!selection || selection.toString().length < 20) return;
      var node = selection.anchorNode;
      while (node) {
        if (node === articleBody) break;
        node = node.parentNode;
      }
      if (!node) return;
      try {
        e.clipboardData.setData('text/plain', selection.toString() + '\n\n' + t('copySource') + document.title + '\n' + location.href);
        e.preventDefault();
        showToast();
      } catch (err) { /* silent */ }
    });
  }

  function fitHeroTitle() {
    var el = document.querySelector('.article-hero-title');
    if (!el) return;
    el.style.fontSize = '';
    var fs = parseFloat(getComputedStyle(el).fontSize);
    var lh = fs * 1.3;
    while (el.offsetHeight > Math.ceil(lh * 3) + 2 && fs > 14) {
      fs -= 1;
      el.style.fontSize = fs + 'px';
      lh = fs * 1.3;
    }
  }
  function runFitAfterLayout() {
    requestAnimationFrame(function () { requestAnimationFrame(fitHeroTitle); });
  }
  if (document.fonts && document.fonts.ready) {
    document.fonts.ready.then(runFitAfterLayout);
  } else {
    window.addEventListener('load', runFitAfterLayout);
  }
  var resizeTimer;
  window.addEventListener('resize', function () {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(fitHeroTitle, 150);
  });

})();
