#!/usr/bin/env python3
"""
stories.html / en/stories.html / es/stories.html の記事一覧セクションを
js/article.js + 各記事HTML から静的生成する。

使い方（プロジェクトルートで実行）:
    python3 scripts/build-stories.py            # JA（デフォルト）
    python3 scripts/build-stories.py --lang en  # 英語版
    python3 scripts/build-stories.py --lang es  # スペイン語版
    python3 scripts/build-stories.py --lang all # 3言語まとめて

何をするか:
    1. js/article.js の ARTICLES / SERIES 配列を正規表現で抽出
    2. 各 articles[/<lang>]/*.html の og:description / og:title から
       カテゴリごとのカードを生成（EN/ESは翻訳済み記事のみ）
    3. 出力ファイルの <!-- BEGIN: category-sections --> ～ <!-- END: ~ -->
       の区間を生成内容で置換

JS無効でも全カードが見える設計（4件目以降は recent-card--collapsed クラス付き、
JS有効時のみ非表示にして「もっと見る」ボタンを出す）。

ソート順: シリーズ所属記事はSERIES定義順 → 単発記事は date 降順
"""

import argparse
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTICLE_JS = ROOT / "js" / "article.js"

BEGIN_MARKER = "<!-- BEGIN: category-sections (auto-generated by scripts/build-stories.py) -->"
END_MARKER = "<!-- END: category-sections -->"

# ─────────────────────────────────────────────
# 言語別設定
# ─────────────────────────────────────────────

# (key, label_ja, label_en, label_es, match_fn)
CATEGORIES = [
    ("costa-rica",  "コスタリカ",     "Costa Rica",     "Costa Rica",     lambda a: a["category"] == "costa-rica"),
    ("nicaragua",   "ニカラグア",     "Nicaragua",      "Nicaragua",      lambda a: a["category"] == "nicaragua"),
    ("mexico",      "メキシコ",       "Mexico",         "México",         lambda a: a["category"] == "mexico"),
    ("chile",       "チリ",           "Chile",          "Chile",          lambda a: a["tag"] == "チリ"),
    ("belize",      "ベリーズ",       "Belize",         "Belice",         lambda a: a["tag"] == "ベリーズ"),
    ("panama",      "パナマ",         "Panama",         "Panamá",         lambda a: a["tag"] == "パナマ"),
    ("el-salvador", "エルサルバドル", "El Salvador",    "El Salvador",    lambda a: a["tag"] == "エルサルバドル"),
    ("taiwan",      "台湾",           "Taiwan",         "Taiwán",         lambda a: a["tag"] == "台湾"),
    ("bike",        "ツーリング",     "Touring",        "Moto",           lambda a: (a["category"] == "bike" and a["tag"] not in ("北海道", "北海道ツーリング")) or (a["category"] == "other" and a["tag"] in ("東北", "新潟"))),
    ("hokkaido",    "北海道",         "Hokkaido",       "Hokkaido",       lambda a: a["category"] == "bike" and a["tag"] in ("北海道", "北海道ツーリング")),
    ("camp",        "キャンプ",       "Camping",        "Camping",        lambda a: a["category"] == "camp"),
    ("other",       "その他",         "Other",          "Otros",          lambda a: a["category"] == "other" and a["tag"] not in ("チリ", "ベリーズ", "パナマ", "エルサルバドル", "台湾", "東北", "新潟")),
]

# JA tag (article.js の tag 値) → EN / ES 表示名
TAG_TRANSLATIONS = {
    "en": {
        "コスタリカ": "Costa Rica",
        "ニカラグア": "Nicaragua",
        "メキシコ": "Mexico",
        "チリ": "Chile",
        "ベリーズ": "Belize",
        "パナマ": "Panama",
        "エルサルバドル": "El Salvador",
        "台湾": "Taiwan",
        "北海道": "Hokkaido",
        "北海道ツーリング": "Hokkaido Touring",
        "東北": "Tohoku",
        "新潟": "Niigata",
        "千葉": "Chiba",
        "福島": "Fukushima",
        "山形": "Yamagata",
        "愛知": "Aichi",
        "静岡": "Shizuoka",
        "石川": "Ishikawa",
        "ツーリング": "Touring",
        "キャンプ": "Camping",
        "海外旅行": "International Travel",
        "スペイン語": "Spanish",
    },
    "es": {
        "コスタリカ": "Costa Rica",
        "ニカラグア": "Nicaragua",
        "メキシコ": "México",
        "チリ": "Chile",
        "ベリーズ": "Belice",
        "パナマ": "Panamá",
        "エルサルバドル": "El Salvador",
        "台湾": "Taiwán",
        "北海道": "Hokkaido",
        "北海道ツーリング": "Hokkaido en moto",
        "東北": "Tohoku",
        "新潟": "Niigata",
        "千葉": "Chiba",
        "福島": "Fukushima",
        "山形": "Yamagata",
        "愛知": "Aichi",
        "静岡": "Shizuoka",
        "石川": "Ishikawa",
        "ツーリング": "Moto",
        "キャンプ": "Camping",
        "海外旅行": "Viajes internacionales",
        "スペイン語": "Español",
    },
}

# JA シリーズ名 → EN / ES シリーズ名（番号 ① 等は維持して JA からは "①〜⑨" に対応）
# article.js の SERIES 配列の name フィールドをキーにする。
SERIES_NAME_TRANSLATIONS = {
    "en": {
        "コスタリカ滞在記":     "Costa Rica Stories",
        "ニカラグア旅行記":     "Nicaragua Travel Notes",
        "メキシコ旅行記":       "Mexico Travel Notes",
        "メキシコ周遊記":       "Mexico Tour Notes",
        "チリ旅行記":           "Chile Travel Notes",
        "ベリーズ旅行記":       "Belize Travel Notes",
        "エルサルバドル旅行記": "El Salvador Travel Notes",
        "パナマ旅行記":         "Panama Travel Notes",
        "SR400北海道ツーリング": "SR400 Hokkaido Touring",
        "XSR900北海道ツーリング": "XSR900 Hokkaido Touring",
        "北海道車旅":           "Hokkaido Car Trip",
        "装備編":               "Gear Notes",
    },
    "es": {
        "コスタリカ滞在記":     "Crónicas de Costa Rica",
        "ニカラグア旅行記":     "Crónicas de Nicaragua",
        "メキシコ旅行記":       "Crónicas de México",
        "メキシコ周遊記":       "Recorrido por México",
        "チリ旅行記":           "Crónicas de Chile",
        "ベリーズ旅行記":       "Crónicas de Belice",
        "エルサルバドル旅行記": "Crónicas de El Salvador",
        "パナマ旅行記":         "Crónicas de Panamá",
        "SR400北海道ツーリング": "SR400 Hokkaido en moto",
        "XSR900北海道ツーリング": "XSR900 Hokkaido en moto",
        "北海道車旅":           "Hokkaido en coche",
        "装備編":               "Notas de Equipo",
    },
}

# 番号文字（JA の ①②… を半角の #1 #2 … に変換）
CIRCLED_NUMBERS = "①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳"


def lang_paths(lang):
    """言語ごとの I/O パスを返す。"""
    if lang == "ja":
        return {
            "articles_dir": ROOT / "articles",
            "stories_html": ROOT / "stories.html",
        }
    if lang in ("en", "es"):
        return {
            "articles_dir": ROOT / "articles" / lang,
            "stories_html": ROOT / lang / "stories.html",
        }
    raise ValueError(f"未対応の言語: {lang}")


def lang_strings(lang):
    """ボタンや見出しの文字列。"""
    return {
        "ja": {"more": "もっと見る ({n}件)"},
        "en": {"more": "Show more ({n})"},
        "es": {"more": "Ver más ({n})"},
    }[lang]


def parse_articles_js():
    """article.js から ARTICLES と SERIES を抽出する。"""
    text = ARTICLE_JS.read_text(encoding="utf-8")

    # ARTICLES 配列の中身
    m = re.search(r"\b(?:const|var|let)\s+ARTICLES\s*=\s*\[(.*?)\n\s*\];", text, re.DOTALL)
    if not m:
        raise RuntimeError("ARTICLES 配列が見つかりません")
    articles_block = m.group(1)

    articles = []
    for line in articles_block.splitlines():
        if "file:" not in line:
            continue
        a = {}
        for key in ("file", "title", "category", "tag", "img", "date"):
            mm = re.search(rf"{key}:\s*'([^']*)'", line)
            if mm:
                a[key] = mm.group(1)
        if "file" in a and "title" in a:
            a.setdefault("category", "")
            a.setdefault("tag", "")
            a.setdefault("img", "")
            a.setdefault("date", "")
            articles.append(a)

    # SERIES 配列（記事の所属シリーズと順番）
    m = re.search(r"\b(?:const|var|let)\s+SERIES\s*=\s*\[(.*?)\n\s*\];", text, re.DOTALL)
    if not m:
        raise RuntimeError("SERIES 配列が見つかりません")
    series_block = m.group(1)

    series_order = {}     # file -> (series_idx, position)
    file_to_series = {}   # file -> series_name (JA)
    series_idx = -1
    current_series_name = None
    for line in series_block.splitlines():
        m_name = re.search(r"name:\s*'([^']+)'", line)
        if m_name and "articles:" in line:
            series_idx += 1
            current_series_name = m_name.group(1)
            position = 0
            continue
        mm = re.search(r"file:\s*'([^']+)'", line)
        if mm and series_idx >= 0:
            series_order[mm.group(1)] = (series_idx, position)
            if current_series_name:
                file_to_series[mm.group(1)] = current_series_name
            position += 1

    return articles, series_order, file_to_series


def extract_meta(html_path, prop):
    """og:description / og:title など property=... の content を取り出す。"""
    try:
        text = html_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""
    m = re.search(
        rf'<meta\s+property="{re.escape(prop)}"\s+content="([^"]*)"', text
    )
    return m.group(1) if m else ""


def extract_h1(html_path):
    """記事 HTML の <h1 class="article-hero-title"> の中身を取り出す。"""
    try:
        text = html_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""
    m = re.search(
        r'<h1\s+class="article-hero-title">(.*?)</h1>', text, re.DOTALL
    )
    return m.group(1).strip() if m else ""


def format_date(iso_date, lang):
    """2021-06-18 → 2021年6月 / June 2021 / Junio de 2021"""
    m = re.match(r"(\d{4})-(\d{2})-\d{2}", iso_date or "")
    if not m:
        return ""
    year = m.group(1)
    month = int(m.group(2))
    if lang == "ja":
        return f"{year}年{month}月"
    months_en = ["January", "February", "March", "April", "May", "June",
                 "July", "August", "September", "October", "November", "December"]
    months_es = ["enero", "febrero", "marzo", "abril", "mayo", "junio",
                 "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"]
    if lang == "en":
        return f"{months_en[month-1]} {year}"
    if lang == "es":
        return f"{months_es[month-1].capitalize()} de {year}"
    return iso_date


def split_series_from_h1(h1_html):
    """<h1>の HTML から最後の【...】部分（シリーズタグ）と、それ以外（タイトル）を分ける。
    タイトル部分の <br> はスペースに変換する。"""
    if not h1_html:
        return "", ""
    m = re.search(r"【(.*?)】", h1_html)
    series = m.group(1) if m else ""
    clean = re.sub(r"<br\s*/?>", " ", h1_html, flags=re.IGNORECASE)
    clean = re.sub(r"<[^>]+>", "", clean)        # タグ削除
    clean = re.sub(r"【.*?】", "", clean).strip()
    clean = re.sub(r"\s+", " ", clean)
    return clean, series


def split_series_from_title(title):
    """JA の article.js title 「本文タイトル【シリーズ名①】」を分ける。"""
    m = re.search(r"【(.*?)】", title)
    series = m.group(1) if m else ""
    clean = re.sub(r"【.*?】", "", title).strip()
    return clean, series


def translate_series_label(series_label_ja, lang, file_to_series):
    """JA の "ニカラグア旅行記③" を EN/ES に変換する。
    series_label_ja: 'コスタリカ滞在記①' のような JA 文字列
    返り値例 (en): 'Costa Rica Stories #1'"""
    if lang == "ja":
        return series_label_ja
    # 末尾の丸数字を切り出し
    base = series_label_ja
    num_index = ""
    for i, ch in enumerate(CIRCLED_NUMBERS, start=1):
        if base.endswith(ch):
            num_index = f"#{i}"
            base = base[:-1]
            break
    translated_base = SERIES_NAME_TRANSLATIONS[lang].get(base, base)
    if num_index:
        return f"{translated_base} {num_index}"
    return translated_base


def make_card_html(article, lang, og_desc, h1_clean, h1_series_label,
                   tag_label, file_to_series, is_collapsed):
    """カード HTML を生成。
    タイトル/説明は lang ごとに og データを使う。
    series_label は file_to_series 由来（JA）を翻訳する。"""
    # タイトル: JA は article.js の title から
    # EN/ES は og:title を使い、末尾の "| Series #N" や " — Series #N" を切り落とす
    if lang == "ja":
        title_clean, _ = split_series_from_title(article["title"])
    else:
        og_title = article.get("_og_title", "")
        if og_title:
            # 末尾の ` | ...` や ` — ...` を切り落とす（最後の出現のみ）
            for sep in (" | ", " — ", " – ", " - "):
                idx = og_title.rfind(sep)
                if idx > 0:
                    og_title = og_title[:idx]
                    break
            title_clean = og_title.strip()
        else:
            title_clean = h1_clean or article["title"]

    # シリーズ名表示
    if lang == "ja":
        # JA: article.js の title 末尾の【...】を拾う
        _, display_series = split_series_from_title(article["title"])
    else:
        # EN/ES: 翻訳済み記事の <h1> 末尾の【...】を使う
        display_series = h1_series_label or ""

    # 画像パス: lang ごとに修正
    img_src = article["img"]
    if img_src.startswith("../"):
        # JA: "../images/foo.jpg" -> "images/foo.jpg"
        # EN/ES: "../images/foo.jpg" -> "../images/foo.jpg"  (en/stories.html から見たパス)
        if lang == "ja":
            img_src = img_src[3:]
        # else: 維持（en/stories.html / es/stories.html から見ても "../images/" でちょうど良い）

    date_iso = article.get("date", "")
    date_disp = format_date(date_iso, lang)

    # リンク先: lang ごと
    if lang == "ja":
        href = "articles/" + article["file"]
    else:
        href = "../articles/" + lang + "/" + article["file"]

    classes = ["recent-card"]
    if is_collapsed:
        classes.append("recent-card--collapsed")

    parts = []
    parts.append(f'<a class="{" ".join(classes)}" href="{html.escape(href)}">')
    if img_src:
        alt = html.escape(title_clean, quote=True)
        parts.append(f'  <div class="recent-card-img"><img src="{html.escape(img_src)}" alt="{alt}" loading="lazy"></div>')
    parts.append('  <div class="recent-card-body">')
    parts.append(f'    <div class="recent-card-tag">{html.escape(tag_label)}</div>')
    if display_series:
        parts.append(f'    <div class="recent-card-series">{html.escape(display_series)}</div>')
    parts.append(f'    <h3 class="recent-card-title">{html.escape(title_clean)}</h3>')
    if og_desc:
        parts.append(f'    <p class="recent-card-desc">{html.escape(og_desc)}</p>')
    if date_disp:
        parts.append(f'    <time class="recent-card-date" datetime="{html.escape(date_iso)}">{html.escape(date_disp)}</time>')
    parts.append('  </div>')
    parts.append('</a>')
    return "\n      ".join(parts)


def build_section(cat_key, cat_label, cards, more_text):
    cards_block = "\n      ".join(cards)
    extra_count = max(0, len(cards) - 3)
    more_btn = ""
    if extra_count > 0:
        msg = more_text.format(n=extra_count)
        more_btn = (
            f'\n    <div class="cat-section-more-wrap" data-extra="{extra_count}">'
            f'<button class="filter-btn cat-section-more-btn">{html.escape(msg)}</button></div>'
        )
    return f"""  <section class="cat-section" data-cat="{html.escape(cat_key)}">
    <div class="cat-section-heading">
      <span class="cat-section-label">{html.escape(cat_label)}</span>
      <div class="cat-section-rule"></div>
    </div>
    <div class="cat-grid">
      {cards_block}
    </div>{more_btn}
  </section>"""


def build_for_lang(lang):
    paths = lang_paths(lang)
    strings = lang_strings(lang)
    articles_dir = paths["articles_dir"]
    stories_html_path = paths["stories_html"]

    if not stories_html_path.exists():
        raise RuntimeError(
            f"出力先が見つかりません: {stories_html_path} — 先に skeleton を作成してください"
        )

    articles, series_order, file_to_series = parse_articles_js()

    # 言語ごとに、翻訳済み記事のみフィルタ
    if lang in ("en", "es"):
        translated = []
        for a in articles:
            article_path = articles_dir / a["file"]
            if article_path.exists():
                translated.append(a)
        articles_for_lang = translated
    else:
        articles_for_lang = articles

    print(f"[{lang}] 対象記事 {len(articles_for_lang)}件 / SERIES登録 {len(series_order)}件",
          file=sys.stderr)

    # 各記事の og:description / og:title / h1 を取得
    article_meta = {}
    for a in articles_for_lang:
        path = articles_dir / a["file"]
        og_desc = extract_meta(path, "og:description")
        og_title = extract_meta(path, "og:title")
        h1 = extract_h1(path)
        h1_clean, h1_series_label = split_series_from_h1(h1)
        article_meta[a["file"]] = {
            "og_desc": og_desc,
            "og_title": og_title,
            "h1_clean": h1_clean,
            "h1_series_label": h1_series_label,
        }

    sections_html = []
    seen = set()
    for entry in CATEGORIES:
        cat_key = entry[0]
        cat_label = entry[{"ja": 1, "en": 2, "es": 3}[lang]]
        match_fn = entry[4]
        matched = [a for a in articles_for_lang if match_fn(a)]
        if not matched:
            continue
        # ソート
        series_articles = [a for a in matched if a["file"] in series_order]
        single_articles = [a for a in matched if a["file"] not in series_order]
        series_articles.sort(key=lambda a: series_order[a["file"]])
        single_articles.sort(key=lambda a: a.get("date", ""), reverse=True)
        ordered = series_articles + single_articles

        cards_html = []
        for idx, a in enumerate(ordered):
            seen.add(a["file"])
            meta = article_meta[a["file"]]
            tag_ja = a.get("tag", "")
            if lang == "ja":
                tag_label = tag_ja
            else:
                tag_label = TAG_TRANSLATIONS.get(lang, {}).get(tag_ja, tag_ja)
            a_with_og = dict(a)
            a_with_og["_og_title"] = meta["og_title"]
            cards_html.append(make_card_html(
                article=a_with_og,
                lang=lang,
                og_desc=meta["og_desc"],
                h1_clean=meta["h1_clean"],
                h1_series_label=meta["h1_series_label"],
                tag_label=tag_label,
                file_to_series=file_to_series,
                is_collapsed=(idx >= 3),
            ))
        sections_html.append(build_section(cat_key, cat_label, cards_html, strings["more"]))

    unseen = [a["file"] for a in articles_for_lang if a["file"] not in seen]
    if unseen:
        print(f"⚠ [{lang}] どのカテゴリにも該当しない記事 {len(unseen)}件:", file=sys.stderr)
        for f in unseen:
            print(f"   {f}", file=sys.stderr)

    generated = "\n" + "\n".join(sections_html) + "\n"

    # 置換
    stories = stories_html_path.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(stories):
        raise RuntimeError(
            f"{stories_html_path.name} にマーカーが見つかりません: "
            f"{BEGIN_MARKER!r} ～ {END_MARKER!r}"
        )

    new_block = BEGIN_MARKER + generated + END_MARKER
    new_stories = pattern.sub(lambda _m: new_block, stories)
    stories_html_path.write_text(new_stories, encoding="utf-8")
    print(f"OK: [{lang}] {stories_html_path.relative_to(ROOT)} を更新 "
          f"({len(sections_html)}カテゴリ / {len(seen)}記事)", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description="stories.html の記事一覧を再生成する")
    parser.add_argument("--lang", default="ja", choices=["ja", "en", "es", "all"],
                        help="出力言語（既定: ja）")
    args = parser.parse_args()

    langs = ["ja", "en", "es"] if args.lang == "all" else [args.lang]
    for lang in langs:
        build_for_lang(lang)


if __name__ == "__main__":
    main()
