#!/usr/bin/env python3
"""
stories.html の記事一覧セクションを js/article.js + 各記事HTML から静的生成する。

使い方（プロジェクトルートで実行）:
    python3 scripts/build-stories.py

何をするか:
    1. js/article.js の ARTICLES / SERIES 配列を正規表現で抽出
    2. 各 articles/*.html の <meta property="og:description"> を抽出
    3. カテゴリごとに記事カード（タイトル・説明・カテゴリ・日付・URL・<img alt>）を生成
    4. stories.html の <!-- BEGIN: category-sections --> ～ <!-- END: category-sections -->
       の区間を生成内容で置換

JS無効でも全カードが見える設計（4件目以降は recent-card--collapsed クラス付き、
JS有効時のみ非表示にして「もっと見る」ボタンを出す）。

ソート順: シリーズ所属記事はSERIES定義順 → 単発記事は date 降順
"""

import html
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTICLE_JS = ROOT / "js" / "article.js"
ARTICLES_DIR = ROOT / "articles"
STORIES_HTML = ROOT / "stories.html"

BEGIN_MARKER = "<!-- BEGIN: category-sections (auto-generated by scripts/build-stories.py) -->"
END_MARKER = "<!-- END: category-sections -->"

# stories.html 内のフィルタボタンと一致させる
CATEGORIES = [
    ("costa-rica",  "コスタリカ",     lambda a: a["category"] == "costa-rica"),
    ("nicaragua",   "ニカラグア",     lambda a: a["category"] == "nicaragua"),
    ("mexico",      "メキシコ",       lambda a: a["category"] == "mexico"),
    ("chile",       "チリ",           lambda a: a["tag"] == "チリ"),
    ("belize",      "ベリーズ",       lambda a: a["tag"] == "ベリーズ"),
    ("panama",      "パナマ",         lambda a: a["tag"] == "パナマ"),
    ("el-salvador", "エルサルバドル", lambda a: a["tag"] == "エルサルバドル"),
    ("taiwan",      "台湾",           lambda a: a["tag"] == "台湾"),
    ("bike",        "ツーリング",     lambda a: (a["category"] == "bike" and a["tag"] not in ("北海道", "北海道ツーリング")) or (a["category"] == "other" and a["tag"] in ("東北", "新潟"))),
    ("hokkaido",    "北海道",         lambda a: a["category"] == "bike" and a["tag"] in ("北海道", "北海道ツーリング")),
    ("camp",        "キャンプ",       lambda a: a["category"] == "camp"),
    ("other",       "その他",         lambda a: a["category"] == "other" and a["tag"] not in ("チリ", "ベリーズ", "パナマ", "エルサルバドル", "台湾", "東北", "新潟")),
]


def parse_articles_js():
    """article.js から ARTICLES と SERIES を抽出する。"""
    text = ARTICLE_JS.read_text(encoding="utf-8")

    # ARTICLES 配列の中身を取り出す
    m = re.search(r"\b(?:const|var|let)\s+ARTICLES\s*=\s*\[(.*?)\n\s*\];", text, re.DOTALL)
    if not m:
        raise RuntimeError("ARTICLES 配列が見つかりません")
    articles_block = m.group(1)

    articles = []
    for line in articles_block.splitlines():
        if "file:" not in line:
            continue
        a = {}
        for key in ("file", "title", "category", "tag", "img", "date"):
            mm = re.search(rf"{key}:\s*'([^']*)'", line)
            if mm:
                a[key] = mm.group(1)
        if "file" in a and "title" in a:
            a.setdefault("category", "")
            a.setdefault("tag", "")
            a.setdefault("img", "")
            a.setdefault("date", "")
            articles.append(a)

    # SERIES 配列の中身（記事の所属シリーズと順番）
    m = re.search(r"\b(?:const|var|let)\s+SERIES\s*=\s*\[(.*?)\n\s*\];", text, re.DOTALL)
    if not m:
        raise RuntimeError("SERIES 配列が見つかりません")
    series_block = m.group(1)

    series_order = {}  # file -> (series_idx, position)
    series_idx = -1
    for line in series_block.splitlines():
        if "{ name:" in line and "articles:" in line:
            series_idx += 1
            position = 0
            continue
        mm = re.search(r"file:\s*'([^']+)'", line)
        if mm and series_idx >= 0:
            series_order[mm.group(1)] = (series_idx, position)
            position += 1

    return articles, series_order


def extract_og_description(html_path):
    try:
        text = html_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""
    m = re.search(r'<meta\s+property="og:description"\s+content="([^"]*)"', text)
    return m.group(1) if m else ""


def format_date_jp(iso_date):
    """2021-06-18 -> 2021年6月"""
    m = re.match(r"(\d{4})-(\d{2})-\d{2}", iso_date or "")
    if not m:
        return ""
    return f"{m.group(1)}年{int(m.group(2))}月"


def split_series_from_title(title):
    """「本文タイトル【シリーズ名①】」を ('本文タイトル', 'シリーズ名①') に分ける。"""
    m = re.search(r"【(.*?)】", title)
    series = m.group(1) if m else ""
    clean = re.sub(r"【.*?】", "", title).strip()
    return clean, series


def make_card_html(article, og_desc, is_collapsed):
    title_clean, series = split_series_from_title(article["title"])
    img_src = article["img"].replace("../", "") if article["img"] else ""
    date_iso = article.get("date", "")
    date_jp = format_date_jp(date_iso)
    href = "articles/" + article["file"]

    classes = ["recent-card"]
    if is_collapsed:
        classes.append("recent-card--collapsed")

    parts = []
    parts.append(f'<a class="{" ".join(classes)}" href="{html.escape(href)}">')
    if img_src:
        alt = html.escape(title_clean, quote=True)
        parts.append(f'  <div class="recent-card-img"><img src="{html.escape(img_src)}" alt="{alt}" loading="lazy"></div>')
    parts.append('  <div class="recent-card-body">')
    parts.append(f'    <div class="recent-card-tag">{html.escape(article.get("tag", ""))}</div>')
    if series:
        parts.append(f'    <div class="recent-card-series">{html.escape(series)}</div>')
    parts.append(f'    <h3 class="recent-card-title">{html.escape(title_clean)}</h3>')
    if og_desc:
        parts.append(f'    <p class="recent-card-desc">{html.escape(og_desc)}</p>')
    if date_jp:
        parts.append(f'    <time class="recent-card-date" datetime="{html.escape(date_iso)}">{html.escape(date_jp)}</time>')
    parts.append('  </div>')
    parts.append('</a>')
    return "\n      ".join(parts)


def build_section(cat_key, cat_label, cat_articles, og_descs):
    cards_html = []
    for idx, a in enumerate(cat_articles):
        cards_html.append(make_card_html(a, og_descs.get(a["file"], ""), is_collapsed=(idx >= 3)))
    cards_block = "\n      ".join(cards_html)

    extra_count = max(0, len(cat_articles) - 3)
    more_btn = ""
    if extra_count > 0:
        more_btn = (
            f'\n    <div class="cat-section-more-wrap" data-extra="{extra_count}">'
            f'<button class="filter-btn cat-section-more-btn">もっと見る ({extra_count}件)</button></div>'
        )

    return f"""  <section class="cat-section" data-cat="{html.escape(cat_key)}">
    <div class="cat-section-heading">
      <span class="cat-section-label">{html.escape(cat_label)}</span>
      <div class="cat-section-rule"></div>
    </div>
    <div class="cat-grid">
      {cards_block}
    </div>{more_btn}
  </section>"""


def main():
    articles, series_order = parse_articles_js()
    print(f"ARTICLES: {len(articles)}件 / SERIES登録: {len(series_order)}件", file=sys.stderr)

    og_descs = {}
    for a in articles:
        path = ARTICLES_DIR / a["file"]
        og_descs[a["file"]] = extract_og_description(path)

    sections_html = []
    seen = set()
    for cat_key, cat_label, match_fn in CATEGORIES:
        matched = [a for a in articles if match_fn(a)]
        # ソート: シリーズ所属優先、シリーズ内は定義順、単発は date 降順
        def sort_key(a):
            order = series_order.get(a["file"])
            if order is not None:
                return (0, order[0], order[1])
            return (1, 0, 0)
        # 単発の date 降順は2段階目
        series_articles = [a for a in matched if a["file"] in series_order]
        single_articles = [a for a in matched if a["file"] not in series_order]
        series_articles.sort(key=lambda a: series_order[a["file"]])
        single_articles.sort(key=lambda a: a.get("date", ""), reverse=True)
        ordered = series_articles + single_articles
        if not ordered:
            continue
        for a in ordered:
            seen.add(a["file"])
        sections_html.append(build_section(cat_key, cat_label, ordered, og_descs))

    # どのカテゴリにも含まれなかった記事を警告
    unseen = [a["file"] for a in articles if a["file"] not in seen]
    if unseen:
        print(f"⚠ どのカテゴリフィルタにも該当しない記事 {len(unseen)}件:", file=sys.stderr)
        for f in unseen:
            print(f"   {f}", file=sys.stderr)

    generated = "\n" + "\n".join(sections_html) + "\n"

    # stories.html 内のマーカー区間を置換
    stories = STORIES_HTML.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(stories):
        raise RuntimeError(
            f"stories.html にマーカーが見つかりません: {BEGIN_MARKER!r} ～ {END_MARKER!r}"
        )

    new_block = BEGIN_MARKER + generated + END_MARKER
    new_stories = pattern.sub(lambda _m: new_block, stories)
    STORIES_HTML.write_text(new_stories, encoding="utf-8")
    print(f"OK: stories.html を更新 ({len(sections_html)}カテゴリ / {len(seen)}記事)", file=sys.stderr)


if __name__ == "__main__":
    main()
